// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_builder.sql

package lightweightdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAgentBuilderCarrier = `-- name: CreateAgentBuilderCarrier :one
INSERT INTO agent (
    workspace_id, runtime_id, owner_id, name, description, instructions,
    runtime_config, max_concurrent_tasks, custom_env, custom_args, mcp_config,
    model, permission_mode, disabled_runtime_skills, kind, system_key
)
VALUES (
    $1, $2, $3, $4,
    '', $5, '{}'::jsonb, 1, '{}'::jsonb, '[]'::jsonb, '{}'::jsonb,
    $6, 'private', '[]'::jsonb, 'system', $7
)
RETURNING id, workspace_id, runtime_id, owner_id, name, description, instructions, avatar_url, runtime_mode, runtime_config, status, max_concurrent_tasks, custom_env, custom_args, mcp_config, model, thinking_level, service_tier, permission_mode, disabled_runtime_skills, archived_at, archived_by, created_at, updated_at, kind, system_key
`

type CreateAgentBuilderCarrierParams struct {
	WorkspaceID  pgtype.UUID `json:"workspace_id"`
	RuntimeID    pgtype.UUID `json:"runtime_id"`
	OwnerID      pgtype.UUID `json:"owner_id"`
	Name         string      `json:"name"`
	Instructions string      `json:"instructions"`
	Model        pgtype.Text `json:"model"`
	SystemKey    pgtype.Text `json:"system_key"`
}

func (q *Queries) CreateAgentBuilderCarrier(ctx context.Context, arg CreateAgentBuilderCarrierParams) (Agent, error) {
	row := q.db.QueryRow(ctx, createAgentBuilderCarrier,
		arg.WorkspaceID,
		arg.RuntimeID,
		arg.OwnerID,
		arg.Name,
		arg.Instructions,
		arg.Model,
		arg.SystemKey,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RuntimeID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Instructions,
		&i.AvatarUrl,
		&i.RuntimeMode,
		&i.RuntimeConfig,
		&i.Status,
		&i.MaxConcurrentTasks,
		&i.CustomEnv,
		&i.CustomArgs,
		&i.McpConfig,
		&i.Model,
		&i.ThinkingLevel,
		&i.ServiceTier,
		&i.PermissionMode,
		&i.DisabledRuntimeSkills,
		&i.ArchivedAt,
		&i.ArchivedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
		&i.SystemKey,
	)
	return i, err
}

const deleteAgentBuilderCarrier = `-- name: DeleteAgentBuilderCarrier :exec
DELETE FROM agent
WHERE id = $1
  AND workspace_id = $2
  AND kind = 'system'
  AND system_key LIKE 'agent_builder:%'
`

type DeleteAgentBuilderCarrierParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteAgentBuilderCarrier(ctx context.Context, arg DeleteAgentBuilderCarrierParams) error {
	_, err := q.db.Exec(ctx, deleteAgentBuilderCarrier, arg.ID, arg.WorkspaceID)
	return err
}

const deleteAgentBuilderDraft = `-- name: DeleteAgentBuilderDraft :exec
DELETE FROM agent_builder_draft WHERE chat_session_id = $1
`

func (q *Queries) DeleteAgentBuilderDraft(ctx context.Context, chatSessionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAgentBuilderDraft, chatSessionID)
	return err
}

const deleteAgentBuilderDraftsByWorkspace = `-- name: DeleteAgentBuilderDraftsByWorkspace :execrows
DELETE FROM agent_builder_draft WHERE workspace_id = $1
`

func (q *Queries) DeleteAgentBuilderDraftsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAgentBuilderDraftsByWorkspace, workspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAgentBuilderCarrier = `-- name: GetAgentBuilderCarrier :one
SELECT id, workspace_id, runtime_id, owner_id, name, description, instructions, avatar_url, runtime_mode, runtime_config, status, max_concurrent_tasks, custom_env, custom_args, mcp_config, model, thinking_level, service_tier, permission_mode, disabled_runtime_skills, archived_at, archived_by, created_at, updated_at, kind, system_key FROM agent
WHERE id = $1
  AND workspace_id = $2
  AND kind = 'system'
  AND system_key LIKE 'agent_builder:%'
`

type GetAgentBuilderCarrierParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) GetAgentBuilderCarrier(ctx context.Context, arg GetAgentBuilderCarrierParams) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentBuilderCarrier, arg.ID, arg.WorkspaceID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RuntimeID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Instructions,
		&i.AvatarUrl,
		&i.RuntimeMode,
		&i.RuntimeConfig,
		&i.Status,
		&i.MaxConcurrentTasks,
		&i.CustomEnv,
		&i.CustomArgs,
		&i.McpConfig,
		&i.Model,
		&i.ThinkingLevel,
		&i.ServiceTier,
		&i.PermissionMode,
		&i.DisabledRuntimeSkills,
		&i.ArchivedAt,
		&i.ArchivedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
		&i.SystemKey,
	)
	return i, err
}

const getAgentBuilderDraft = `-- name: GetAgentBuilderDraft :one
SELECT chat_session_id, workspace_id, draft, updated_at FROM agent_builder_draft
WHERE chat_session_id = $1
  AND workspace_id = $2
`

type GetAgentBuilderDraftParams struct {
	ChatSessionID pgtype.UUID `json:"chat_session_id"`
	WorkspaceID   pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) GetAgentBuilderDraft(ctx context.Context, arg GetAgentBuilderDraftParams) (AgentBuilderDraft, error) {
	row := q.db.QueryRow(ctx, getAgentBuilderDraft, arg.ChatSessionID, arg.WorkspaceID)
	var i AgentBuilderDraft
	err := row.Scan(
		&i.ChatSessionID,
		&i.WorkspaceID,
		&i.Draft,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentAvatarURLsByWorkspace = `-- name: ListAgentAvatarURLsByWorkspace :many
SELECT avatar_url FROM agent
WHERE workspace_id = $1
  AND avatar_url IS NOT NULL
  AND avatar_url <> ''
`

func (q *Queries) ListAgentAvatarURLsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, listAgentAvatarURLsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Text{}
	for rows.Next() {
		var avatar_url pgtype.Text
		if err := rows.Scan(&avatar_url); err != nil {
			return nil, err
		}
		items = append(items, avatar_url)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSquadAvatarURLsByWorkspace = `-- name: ListSquadAvatarURLsByWorkspace :many
SELECT avatar_url FROM squad
WHERE workspace_id = $1
  AND avatar_url IS NOT NULL
  AND avatar_url <> ''
`

func (q *Queries) ListSquadAvatarURLsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, listSquadAvatarURLsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Text{}
	for rows.Next() {
		var avatar_url pgtype.Text
		if err := rows.Scan(&avatar_url); err != nil {
			return nil, err
		}
		items = append(items, avatar_url)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAgentBuilderCarrier = `-- name: LockAgentBuilderCarrier :one
SELECT id, workspace_id, runtime_id, owner_id, name, description, instructions, avatar_url, runtime_mode, runtime_config, status, max_concurrent_tasks, custom_env, custom_args, mcp_config, model, thinking_level, service_tier, permission_mode, disabled_runtime_skills, archived_at, archived_by, created_at, updated_at, kind, system_key FROM agent
WHERE id = $1
  AND workspace_id = $2
  AND kind = 'system'
  AND system_key LIKE 'agent_builder:%'
FOR UPDATE
`

type LockAgentBuilderCarrierParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) LockAgentBuilderCarrier(ctx context.Context, arg LockAgentBuilderCarrierParams) (Agent, error) {
	row := q.db.QueryRow(ctx, lockAgentBuilderCarrier, arg.ID, arg.WorkspaceID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RuntimeID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Instructions,
		&i.AvatarUrl,
		&i.RuntimeMode,
		&i.RuntimeConfig,
		&i.Status,
		&i.MaxConcurrentTasks,
		&i.CustomEnv,
		&i.CustomArgs,
		&i.McpConfig,
		&i.Model,
		&i.ThinkingLevel,
		&i.ServiceTier,
		&i.PermissionMode,
		&i.DisabledRuntimeSkills,
		&i.ArchivedAt,
		&i.ArchivedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
		&i.SystemKey,
	)
	return i, err
}

const updateAgentBuilderCarrierRuntime = `-- name: UpdateAgentBuilderCarrierRuntime :one
UPDATE agent
SET runtime_id = $1,
    model = $2,
    updated_at = now()
WHERE id = $3
  AND workspace_id = $4
  AND kind = 'system'
  AND system_key LIKE 'agent_builder:%'
RETURNING id, workspace_id, runtime_id, owner_id, name, description, instructions, avatar_url, runtime_mode, runtime_config, status, max_concurrent_tasks, custom_env, custom_args, mcp_config, model, thinking_level, service_tier, permission_mode, disabled_runtime_skills, archived_at, archived_by, created_at, updated_at, kind, system_key
`

type UpdateAgentBuilderCarrierRuntimeParams struct {
	RuntimeID   pgtype.UUID `json:"runtime_id"`
	Model       pgtype.Text `json:"model"`
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) UpdateAgentBuilderCarrierRuntime(ctx context.Context, arg UpdateAgentBuilderCarrierRuntimeParams) (Agent, error) {
	row := q.db.QueryRow(ctx, updateAgentBuilderCarrierRuntime,
		arg.RuntimeID,
		arg.Model,
		arg.ID,
		arg.WorkspaceID,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RuntimeID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Instructions,
		&i.AvatarUrl,
		&i.RuntimeMode,
		&i.RuntimeConfig,
		&i.Status,
		&i.MaxConcurrentTasks,
		&i.CustomEnv,
		&i.CustomArgs,
		&i.McpConfig,
		&i.Model,
		&i.ThinkingLevel,
		&i.ServiceTier,
		&i.PermissionMode,
		&i.DisabledRuntimeSkills,
		&i.ArchivedAt,
		&i.ArchivedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
		&i.SystemKey,
	)
	return i, err
}

const upsertAgentBuilderDraft = `-- name: UpsertAgentBuilderDraft :one
INSERT INTO agent_builder_draft (chat_session_id, workspace_id, draft)
VALUES ($1, $2, $3)
ON CONFLICT (chat_session_id) DO UPDATE
SET draft = EXCLUDED.draft,
    updated_at = now()
RETURNING chat_session_id, workspace_id, draft, updated_at
`

type UpsertAgentBuilderDraftParams struct {
	ChatSessionID pgtype.UUID `json:"chat_session_id"`
	WorkspaceID   pgtype.UUID `json:"workspace_id"`
	Draft         []byte      `json:"draft"`
}

func (q *Queries) UpsertAgentBuilderDraft(ctx context.Context, arg UpsertAgentBuilderDraftParams) (AgentBuilderDraft, error) {
	row := q.db.QueryRow(ctx, upsertAgentBuilderDraft, arg.ChatSessionID, arg.WorkspaceID, arg.Draft)
	var i AgentBuilderDraft
	err := row.Scan(
		&i.ChatSessionID,
		&i.WorkspaceID,
		&i.Draft,
		&i.UpdatedAt,
	)
	return i, err
}
