// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_management.sql

package lightweightdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelAgentTasksByAgent = `-- name: CancelAgentTasksByAgent :many
UPDATE agent_task_queue task
SET status = 'cancelled',
    completed_at = COALESCE(task.completed_at, now()),
    prepare_lease_expires_at = NULL,
    chat_finalize_deferred_at = CASE
        WHEN task.chat_session_id IS NOT NULL
             AND task.status IN ('dispatched', 'waiting_local_directory', 'running') THEN now()
        ELSE task.chat_finalize_deferred_at
    END
WHERE task.workspace_id = $1
  AND task.agent_id = $2
  AND task.status IN ('deferred', 'queued', 'dispatched', 'waiting_local_directory', 'running')
RETURNING task.id, task.workspace_id, task.agent_id, task.runtime_id, task.issue_id, task.chat_session_id, task.squad_id, task.is_leader_task, task.status, task.priority, task.attempt, task.max_attempts, task.parent_task_id, task.session_id, task.work_dir, task.context, task.result, task.error, task.failure_reason, task.trigger_summary, task.force_fresh_session, task.handoff_note, task.wait_reason, task.prepare_lease_expires_at, task.fire_at, task.runtime_mcp_overlay, task.initiator_user_id, task.originator_user_id, task.accountable_user_id, task.originator_source, task.trigger_comment_id, task.coalesced_comment_ids, task.delivered_comment_ids, task.chat_input_task_id, task.chat_finalize_deferred_at, task.escalation_for_task_id, task.delegated_from_task_id, task.retry_of_task_id, task.rerun_of_task_id, task.trigger_evidence_kind, task.trigger_evidence_ref_id, task.session_rollout_missing, task.retired_session_id, task.dispatched_at, task.started_at, task.completed_at, task.created_at, task.tool_bundle_id
`

type CancelAgentTasksByAgentParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	AgentID     pgtype.UUID `json:"agent_id"`
}

func (q *Queries) CancelAgentTasksByAgent(ctx context.Context, arg CancelAgentTasksByAgentParams) ([]AgentTaskQueue, error) {
	rows, err := q.db.Query(ctx, cancelAgentTasksByAgent, arg.WorkspaceID, arg.AgentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentTaskQueue{}
	for rows.Next() {
		var i AgentTaskQueue
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AgentID,
			&i.RuntimeID,
			&i.IssueID,
			&i.ChatSessionID,
			&i.SquadID,
			&i.IsLeaderTask,
			&i.Status,
			&i.Priority,
			&i.Attempt,
			&i.MaxAttempts,
			&i.ParentTaskID,
			&i.SessionID,
			&i.WorkDir,
			&i.Context,
			&i.Result,
			&i.Error,
			&i.FailureReason,
			&i.TriggerSummary,
			&i.ForceFreshSession,
			&i.HandoffNote,
			&i.WaitReason,
			&i.PrepareLeaseExpiresAt,
			&i.FireAt,
			&i.RuntimeMcpOverlay,
			&i.InitiatorUserID,
			&i.OriginatorUserID,
			&i.AccountableUserID,
			&i.OriginatorSource,
			&i.TriggerCommentID,
			&i.CoalescedCommentIds,
			&i.DeliveredCommentIds,
			&i.ChatInputTaskID,
			&i.ChatFinalizeDeferredAt,
			&i.EscalationForTaskID,
			&i.DelegatedFromTaskID,
			&i.RetryOfTaskID,
			&i.RerunOfTaskID,
			&i.TriggerEvidenceKind,
			&i.TriggerEvidenceRefID,
			&i.SessionRolloutMissing,
			&i.RetiredSessionID,
			&i.DispatchedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.ToolBundleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAgentByAvatarURL = `-- name: GetAgentByAvatarURL :one
SELECT id, workspace_id FROM agent
WHERE avatar_url = $1 AND kind = 'user'
LIMIT 1
`

type GetAgentByAvatarURLRow struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) GetAgentByAvatarURL(ctx context.Context, avatarUrl pgtype.Text) (GetAgentByAvatarURLRow, error) {
	row := q.db.QueryRow(ctx, getAgentByAvatarURL, avatarUrl)
	var i GetAgentByAvatarURLRow
	err := row.Scan(&i.ID, &i.WorkspaceID)
	return i, err
}

const getAgentTaskSummary30d = `-- name: GetAgentTaskSummary30d :one
SELECT
    COUNT(*)::int AS run_count,
    COUNT(*) FILTER (WHERE task.status = 'completed')::int AS success_count,
    COUNT(*) FILTER (WHERE task.status = 'failed')::int AS fail_count,
    COALESCE(
        AVG(EXTRACT(EPOCH FROM (task.completed_at - task.started_at)) * 1000)
            FILTER (WHERE task.started_at IS NOT NULL AND task.completed_at IS NOT NULL),
        0
    )::float8 AS avg_duration_ms
FROM agent_task_queue task
JOIN agent ON agent.id = task.agent_id
WHERE task.workspace_id = $1
  AND task.agent_id = $2
  AND agent.kind = 'user'
  AND task.created_at > now() - INTERVAL '30 days'
  AND task.status IN ('completed', 'failed')
`

type GetAgentTaskSummary30dParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	AgentID     pgtype.UUID `json:"agent_id"`
}

type GetAgentTaskSummary30dRow struct {
	RunCount      int32   `json:"run_count"`
	SuccessCount  int32   `json:"success_count"`
	FailCount     int32   `json:"fail_count"`
	AvgDurationMs float64 `json:"avg_duration_ms"`
}

func (q *Queries) GetAgentTaskSummary30d(ctx context.Context, arg GetAgentTaskSummary30dParams) (GetAgentTaskSummary30dRow, error) {
	row := q.db.QueryRow(ctx, getAgentTaskSummary30d, arg.WorkspaceID, arg.AgentID)
	var i GetAgentTaskSummary30dRow
	err := row.Scan(
		&i.RunCount,
		&i.SuccessCount,
		&i.FailCount,
		&i.AvgDurationMs,
	)
	return i, err
}

const getSquadByAvatarURL = `-- name: GetSquadByAvatarURL :one
SELECT id, workspace_id FROM squad
WHERE avatar_url = $1
LIMIT 1
`

type GetSquadByAvatarURLRow struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) GetSquadByAvatarURL(ctx context.Context, avatarUrl pgtype.Text) (GetSquadByAvatarURLRow, error) {
	row := q.db.QueryRow(ctx, getSquadByAvatarURL, avatarUrl)
	var i GetSquadByAvatarURLRow
	err := row.Scan(&i.ID, &i.WorkspaceID)
	return i, err
}

const getWorkspaceAgentActivity30d = `-- name: GetWorkspaceAgentActivity30d :many
SELECT
    atq.agent_id,
    DATE_TRUNC('day', atq.completed_at)::timestamptz AS bucket,
    COUNT(*)::int AS task_count,
    COUNT(*) FILTER (WHERE atq.status = 'failed')::int AS failed_count
FROM agent_task_queue atq
JOIN agent a ON a.id = atq.agent_id
WHERE a.workspace_id = $1
  AND a.kind = 'user'
  AND atq.completed_at IS NOT NULL
  AND atq.completed_at > now() - INTERVAL '30 days'
GROUP BY atq.agent_id, bucket
ORDER BY atq.agent_id, bucket
`

type GetWorkspaceAgentActivity30dRow struct {
	AgentID     pgtype.UUID        `json:"agent_id"`
	Bucket      pgtype.Timestamptz `json:"bucket"`
	TaskCount   int32              `json:"task_count"`
	FailedCount int32              `json:"failed_count"`
}

func (q *Queries) GetWorkspaceAgentActivity30d(ctx context.Context, workspaceID pgtype.UUID) ([]GetWorkspaceAgentActivity30dRow, error) {
	rows, err := q.db.Query(ctx, getWorkspaceAgentActivity30d, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWorkspaceAgentActivity30dRow{}
	for rows.Next() {
		var i GetWorkspaceAgentActivity30dRow
		if err := rows.Scan(
			&i.AgentID,
			&i.Bucket,
			&i.TaskCount,
			&i.FailedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspaceAgentRunCounts = `-- name: GetWorkspaceAgentRunCounts :many
SELECT
    atq.agent_id,
    COUNT(*)::int AS run_count
FROM agent_task_queue atq
JOIN agent a ON a.id = atq.agent_id
WHERE a.workspace_id = $1
  AND a.kind = 'user'
  AND atq.created_at > now() - INTERVAL '30 days'
GROUP BY atq.agent_id
`

type GetWorkspaceAgentRunCountsRow struct {
	AgentID  pgtype.UUID `json:"agent_id"`
	RunCount int32       `json:"run_count"`
}

func (q *Queries) GetWorkspaceAgentRunCounts(ctx context.Context, workspaceID pgtype.UUID) ([]GetWorkspaceAgentRunCountsRow, error) {
	rows, err := q.db.Query(ctx, getWorkspaceAgentRunCounts, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWorkspaceAgentRunCountsRow{}
	for rows.Next() {
		var i GetWorkspaceAgentRunCountsRow
		if err := rows.Scan(&i.AgentID, &i.RunCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentTasksPage = `-- name: ListAgentTasksPage :many
SELECT task.id, task.workspace_id, task.agent_id, task.runtime_id, task.issue_id, task.chat_session_id, task.squad_id, task.is_leader_task, task.status, task.priority, task.attempt, task.max_attempts, task.parent_task_id, task.session_id, task.work_dir, task.context, task.result, task.error, task.failure_reason, task.trigger_summary, task.force_fresh_session, task.handoff_note, task.wait_reason, task.prepare_lease_expires_at, task.fire_at, task.runtime_mcp_overlay, task.initiator_user_id, task.originator_user_id, task.accountable_user_id, task.originator_source, task.trigger_comment_id, task.coalesced_comment_ids, task.delivered_comment_ids, task.chat_input_task_id, task.chat_finalize_deferred_at, task.escalation_for_task_id, task.delegated_from_task_id, task.retry_of_task_id, task.rerun_of_task_id, task.trigger_evidence_kind, task.trigger_evidence_ref_id, task.session_rollout_missing, task.retired_session_id, task.dispatched_at, task.started_at, task.completed_at, task.created_at, task.tool_bundle_id
FROM agent_task_queue task
JOIN agent ON agent.id = task.agent_id
WHERE task.workspace_id = $1
  AND task.agent_id = $2
  AND agent.kind = 'user'
  AND (
      $3::timestamptz IS NULL
      OR (task.created_at, task.id) < ($3::timestamptz, $4::uuid)
  )
ORDER BY task.created_at DESC, task.id DESC
LIMIT $5
`

type ListAgentTasksPageParams struct {
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	AgentID         pgtype.UUID        `json:"agent_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	PageLimit       int32              `json:"page_limit"`
}

func (q *Queries) ListAgentTasksPage(ctx context.Context, arg ListAgentTasksPageParams) ([]AgentTaskQueue, error) {
	rows, err := q.db.Query(ctx, listAgentTasksPage,
		arg.WorkspaceID,
		arg.AgentID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentTaskQueue{}
	for rows.Next() {
		var i AgentTaskQueue
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AgentID,
			&i.RuntimeID,
			&i.IssueID,
			&i.ChatSessionID,
			&i.SquadID,
			&i.IsLeaderTask,
			&i.Status,
			&i.Priority,
			&i.Attempt,
			&i.MaxAttempts,
			&i.ParentTaskID,
			&i.SessionID,
			&i.WorkDir,
			&i.Context,
			&i.Result,
			&i.Error,
			&i.FailureReason,
			&i.TriggerSummary,
			&i.ForceFreshSession,
			&i.HandoffNote,
			&i.WaitReason,
			&i.PrepareLeaseExpiresAt,
			&i.FireAt,
			&i.RuntimeMcpOverlay,
			&i.InitiatorUserID,
			&i.OriginatorUserID,
			&i.AccountableUserID,
			&i.OriginatorSource,
			&i.TriggerCommentID,
			&i.CoalescedCommentIds,
			&i.DeliveredCommentIds,
			&i.ChatInputTaskID,
			&i.ChatFinalizeDeferredAt,
			&i.EscalationForTaskID,
			&i.DelegatedFromTaskID,
			&i.RetryOfTaskID,
			&i.RerunOfTaskID,
			&i.TriggerEvidenceKind,
			&i.TriggerEvidenceRefID,
			&i.SessionRolloutMissing,
			&i.RetiredSessionID,
			&i.DispatchedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.ToolBundleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceAgentTaskSnapshot = `-- name: ListWorkspaceAgentTaskSnapshot :many
SELECT atq.id, atq.workspace_id, atq.agent_id, atq.runtime_id, atq.issue_id, atq.chat_session_id, atq.squad_id, atq.is_leader_task, atq.status, atq.priority, atq.attempt, atq.max_attempts, atq.parent_task_id, atq.session_id, atq.work_dir, atq.context, atq.result, atq.error, atq.failure_reason, atq.trigger_summary, atq.force_fresh_session, atq.handoff_note, atq.wait_reason, atq.prepare_lease_expires_at, atq.fire_at, atq.runtime_mcp_overlay, atq.initiator_user_id, atq.originator_user_id, atq.accountable_user_id, atq.originator_source, atq.trigger_comment_id, atq.coalesced_comment_ids, atq.delivered_comment_ids, atq.chat_input_task_id, atq.chat_finalize_deferred_at, atq.escalation_for_task_id, atq.delegated_from_task_id, atq.retry_of_task_id, atq.rerun_of_task_id, atq.trigger_evidence_kind, atq.trigger_evidence_ref_id, atq.session_rollout_missing, atq.retired_session_id, atq.dispatched_at, atq.started_at, atq.completed_at, atq.created_at, atq.tool_bundle_id
FROM agent_task_queue atq
JOIN agent a ON a.id = atq.agent_id
WHERE a.workspace_id = $1
  AND a.kind = 'user'
  AND atq.status IN ('queued', 'dispatched', 'running', 'waiting_local_directory')

UNION ALL

SELECT latest.id, latest.workspace_id, latest.agent_id, latest.runtime_id, latest.issue_id, latest.chat_session_id, latest.squad_id, latest.is_leader_task, latest.status, latest.priority, latest.attempt, latest.max_attempts, latest.parent_task_id, latest.session_id, latest.work_dir, latest.context, latest.result, latest.error, latest.failure_reason, latest.trigger_summary, latest.force_fresh_session, latest.handoff_note, latest.wait_reason, latest.prepare_lease_expires_at, latest.fire_at, latest.runtime_mcp_overlay, latest.initiator_user_id, latest.originator_user_id, latest.accountable_user_id, latest.originator_source, latest.trigger_comment_id, latest.coalesced_comment_ids, latest.delivered_comment_ids, latest.chat_input_task_id, latest.chat_finalize_deferred_at, latest.escalation_for_task_id, latest.delegated_from_task_id, latest.retry_of_task_id, latest.rerun_of_task_id, latest.trigger_evidence_kind, latest.trigger_evidence_ref_id, latest.session_rollout_missing, latest.retired_session_id, latest.dispatched_at, latest.started_at, latest.completed_at, latest.created_at, latest.tool_bundle_id
FROM agent a
JOIN LATERAL (
    SELECT atq.id, atq.workspace_id, atq.agent_id, atq.runtime_id, atq.issue_id, atq.chat_session_id, atq.squad_id, atq.is_leader_task, atq.status, atq.priority, atq.attempt, atq.max_attempts, atq.parent_task_id, atq.session_id, atq.work_dir, atq.context, atq.result, atq.error, atq.failure_reason, atq.trigger_summary, atq.force_fresh_session, atq.handoff_note, atq.wait_reason, atq.prepare_lease_expires_at, atq.fire_at, atq.runtime_mcp_overlay, atq.initiator_user_id, atq.originator_user_id, atq.accountable_user_id, atq.originator_source, atq.trigger_comment_id, atq.coalesced_comment_ids, atq.delivered_comment_ids, atq.chat_input_task_id, atq.chat_finalize_deferred_at, atq.escalation_for_task_id, atq.delegated_from_task_id, atq.retry_of_task_id, atq.rerun_of_task_id, atq.trigger_evidence_kind, atq.trigger_evidence_ref_id, atq.session_rollout_missing, atq.retired_session_id, atq.dispatched_at, atq.started_at, atq.completed_at, atq.created_at, atq.tool_bundle_id
    FROM agent_task_queue atq
    WHERE atq.agent_id = a.id
      AND atq.status IN ('completed', 'failed')
    ORDER BY atq.completed_at DESC NULLS LAST, atq.created_at DESC, atq.id DESC
    LIMIT 1
) latest ON TRUE
WHERE a.workspace_id = $1
  AND a.kind = 'user'
`

func (q *Queries) ListWorkspaceAgentTaskSnapshot(ctx context.Context, workspaceID pgtype.UUID) ([]AgentTaskQueue, error) {
	rows, err := q.db.Query(ctx, listWorkspaceAgentTaskSnapshot, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentTaskQueue{}
	for rows.Next() {
		var i AgentTaskQueue
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AgentID,
			&i.RuntimeID,
			&i.IssueID,
			&i.ChatSessionID,
			&i.SquadID,
			&i.IsLeaderTask,
			&i.Status,
			&i.Priority,
			&i.Attempt,
			&i.MaxAttempts,
			&i.ParentTaskID,
			&i.SessionID,
			&i.WorkDir,
			&i.Context,
			&i.Result,
			&i.Error,
			&i.FailureReason,
			&i.TriggerSummary,
			&i.ForceFreshSession,
			&i.HandoffNote,
			&i.WaitReason,
			&i.PrepareLeaseExpiresAt,
			&i.FireAt,
			&i.RuntimeMcpOverlay,
			&i.InitiatorUserID,
			&i.OriginatorUserID,
			&i.AccountableUserID,
			&i.OriginatorSource,
			&i.TriggerCommentID,
			&i.CoalescedCommentIds,
			&i.DeliveredCommentIds,
			&i.ChatInputTaskID,
			&i.ChatFinalizeDeferredAt,
			&i.EscalationForTaskID,
			&i.DelegatedFromTaskID,
			&i.RetryOfTaskID,
			&i.RerunOfTaskID,
			&i.TriggerEvidenceKind,
			&i.TriggerEvidenceRefID,
			&i.SessionRolloutMissing,
			&i.RetiredSessionID,
			&i.DispatchedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.ToolBundleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgentAvatar = `-- name: UpdateAgentAvatar :one
UPDATE agent
SET avatar_url = $1, updated_at = now()
WHERE id = $2 AND workspace_id = $3 AND kind = 'user'
RETURNING id, workspace_id, runtime_id, owner_id, name, description, instructions, avatar_url, runtime_mode, runtime_config, status, max_concurrent_tasks, custom_env, custom_args, mcp_config, model, thinking_level, service_tier, permission_mode, disabled_runtime_skills, archived_at, archived_by, created_at, updated_at, kind, system_key
`

type UpdateAgentAvatarParams struct {
	AvatarUrl   pgtype.Text `json:"avatar_url"`
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) UpdateAgentAvatar(ctx context.Context, arg UpdateAgentAvatarParams) (Agent, error) {
	row := q.db.QueryRow(ctx, updateAgentAvatar, arg.AvatarUrl, arg.ID, arg.WorkspaceID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RuntimeID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Instructions,
		&i.AvatarUrl,
		&i.RuntimeMode,
		&i.RuntimeConfig,
		&i.Status,
		&i.MaxConcurrentTasks,
		&i.CustomEnv,
		&i.CustomArgs,
		&i.McpConfig,
		&i.Model,
		&i.ThinkingLevel,
		&i.ServiceTier,
		&i.PermissionMode,
		&i.DisabledRuntimeSkills,
		&i.ArchivedAt,
		&i.ArchivedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
		&i.SystemKey,
	)
	return i, err
}

const updateSquadAvatar = `-- name: UpdateSquadAvatar :one
UPDATE squad
SET avatar_url = $1, updated_at = now()
WHERE id = $2 AND workspace_id = $3
RETURNING id, workspace_id, name, description, instructions, leader_id, creator_id, avatar_url, archived_at, archived_by, created_at, updated_at
`

type UpdateSquadAvatarParams struct {
	AvatarUrl   pgtype.Text `json:"avatar_url"`
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) UpdateSquadAvatar(ctx context.Context, arg UpdateSquadAvatarParams) (Squad, error) {
	row := q.db.QueryRow(ctx, updateSquadAvatar, arg.AvatarUrl, arg.ID, arg.WorkspaceID)
	var i Squad
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Instructions,
		&i.LeaderID,
		&i.CreatorID,
		&i.AvatarUrl,
		&i.ArchivedAt,
		&i.ArchivedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
