// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat.sql

package lightweightdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveTasksByChatSession = `-- name: CountActiveTasksByChatSession :one
SELECT count(*) FROM agent_task_queue
WHERE workspace_id = $1
  AND chat_session_id = $2
  AND status IN ('deferred', 'queued', 'dispatched', 'waiting_local_directory', 'running')
`

type CountActiveTasksByChatSessionParams struct {
	WorkspaceID   pgtype.UUID `json:"workspace_id"`
	ChatSessionID pgtype.UUID `json:"chat_session_id"`
}

func (q *Queries) CountActiveTasksByChatSession(ctx context.Context, arg CountActiveTasksByChatSessionParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveTasksByChatSession, arg.WorkspaceID, arg.ChatSessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChatDraftRestore = `-- name: CreateChatDraftRestore :one
INSERT INTO chat_draft_restore (chat_session_id, task_id, content)
VALUES ($1, $2, $3)
ON CONFLICT (chat_session_id, task_id) DO UPDATE SET content = EXCLUDED.content
RETURNING id, chat_session_id, task_id, content, created_at
`

type CreateChatDraftRestoreParams struct {
	ChatSessionID pgtype.UUID `json:"chat_session_id"`
	TaskID        pgtype.UUID `json:"task_id"`
	Content       string      `json:"content"`
}

func (q *Queries) CreateChatDraftRestore(ctx context.Context, arg CreateChatDraftRestoreParams) (ChatDraftRestore, error) {
	row := q.db.QueryRow(ctx, createChatDraftRestore, arg.ChatSessionID, arg.TaskID, arg.Content)
	var i ChatDraftRestore
	err := row.Scan(
		&i.ID,
		&i.ChatSessionID,
		&i.TaskID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const createChatMessage = `-- name: CreateChatMessage :one
INSERT INTO chat_message (
    chat_session_id, role, content, task_id, failure_reason, elapsed_ms,
    message_kind, idempotency_key, request_hash
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9
)
RETURNING id, chat_session_id, role, content, task_id, failure_reason, elapsed_ms, message_kind, idempotency_key, request_hash, created_at
`

type CreateChatMessageParams struct {
	ChatSessionID  pgtype.UUID `json:"chat_session_id"`
	Role           string      `json:"role"`
	Content        string      `json:"content"`
	TaskID         pgtype.UUID `json:"task_id"`
	FailureReason  pgtype.Text `json:"failure_reason"`
	ElapsedMs      pgtype.Int8 `json:"elapsed_ms"`
	MessageKind    string      `json:"message_kind"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
	RequestHash    pgtype.Text `json:"request_hash"`
}

func (q *Queries) CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, createChatMessage,
		arg.ChatSessionID,
		arg.Role,
		arg.Content,
		arg.TaskID,
		arg.FailureReason,
		arg.ElapsedMs,
		arg.MessageKind,
		arg.IdempotencyKey,
		arg.RequestHash,
	)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.ChatSessionID,
		&i.Role,
		&i.Content,
		&i.TaskID,
		&i.FailureReason,
		&i.ElapsedMs,
		&i.MessageKind,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.CreatedAt,
	)
	return i, err
}

const createChatSession = `-- name: CreateChatSession :one
INSERT INTO chat_session (
    workspace_id, agent_id, creator_id, runtime_id, title, status
)
VALUES (
    $1, $2, $3,
    $4, $5, 'active'
)
RETURNING id, workspace_id, agent_id, creator_id, runtime_id, title, session_id, work_dir, status, created_at, updated_at
`

type CreateChatSessionParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	AgentID     pgtype.UUID `json:"agent_id"`
	CreatorID   pgtype.UUID `json:"creator_id"`
	RuntimeID   pgtype.UUID `json:"runtime_id"`
	Title       string      `json:"title"`
}

func (q *Queries) CreateChatSession(ctx context.Context, arg CreateChatSessionParams) (ChatSession, error) {
	row := q.db.QueryRow(ctx, createChatSession,
		arg.WorkspaceID,
		arg.AgentID,
		arg.CreatorID,
		arg.RuntimeID,
		arg.Title,
	)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AgentID,
		&i.CreatorID,
		&i.RuntimeID,
		&i.Title,
		&i.SessionID,
		&i.WorkDir,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createChatTask = `-- name: CreateChatTask :one
WITH identity AS (
    SELECT gen_random_uuid() AS id
)
INSERT INTO agent_task_queue (
    id, workspace_id, agent_id, runtime_id, chat_session_id, status, priority,
    session_id, work_dir, context, initiator_user_id, originator_user_id,
    accountable_user_id, originator_source, chat_input_task_id,
    trigger_evidence_kind, trigger_evidence_ref_id, tool_bundle_id
)
SELECT
    identity.id, $1, $2, $3,
    $4, 'queued', 2, $5, $6,
    '{}'::jsonb, $7, $7, $7,
    'direct_human', identity.id, 'chat', $4,
    (SELECT head.bundle_id FROM agent_tool_bundle_head head
     WHERE head.workspace_id = $1 AND head.agent_id = $2)
FROM identity
RETURNING id, workspace_id, agent_id, runtime_id, issue_id, chat_session_id, squad_id, is_leader_task, status, priority, attempt, max_attempts, parent_task_id, session_id, work_dir, context, result, error, failure_reason, trigger_summary, force_fresh_session, handoff_note, wait_reason, prepare_lease_expires_at, fire_at, runtime_mcp_overlay, initiator_user_id, originator_user_id, accountable_user_id, originator_source, trigger_comment_id, coalesced_comment_ids, delivered_comment_ids, chat_input_task_id, chat_finalize_deferred_at, escalation_for_task_id, delegated_from_task_id, retry_of_task_id, rerun_of_task_id, trigger_evidence_kind, trigger_evidence_ref_id, session_rollout_missing, retired_session_id, dispatched_at, started_at, completed_at, created_at, tool_bundle_id
`

type CreateChatTaskParams struct {
	WorkspaceID   pgtype.UUID `json:"workspace_id"`
	AgentID       pgtype.UUID `json:"agent_id"`
	RuntimeID     pgtype.UUID `json:"runtime_id"`
	ChatSessionID pgtype.UUID `json:"chat_session_id"`
	SessionID     pgtype.Text `json:"session_id"`
	WorkDir       pgtype.Text `json:"work_dir"`
	UserID        pgtype.UUID `json:"user_id"`
}

func (q *Queries) CreateChatTask(ctx context.Context, arg CreateChatTaskParams) (AgentTaskQueue, error) {
	row := q.db.QueryRow(ctx, createChatTask,
		arg.WorkspaceID,
		arg.AgentID,
		arg.RuntimeID,
		arg.ChatSessionID,
		arg.SessionID,
		arg.WorkDir,
		arg.UserID,
	)
	var i AgentTaskQueue
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AgentID,
		&i.RuntimeID,
		&i.IssueID,
		&i.ChatSessionID,
		&i.SquadID,
		&i.IsLeaderTask,
		&i.Status,
		&i.Priority,
		&i.Attempt,
		&i.MaxAttempts,
		&i.ParentTaskID,
		&i.SessionID,
		&i.WorkDir,
		&i.Context,
		&i.Result,
		&i.Error,
		&i.FailureReason,
		&i.TriggerSummary,
		&i.ForceFreshSession,
		&i.HandoffNote,
		&i.WaitReason,
		&i.PrepareLeaseExpiresAt,
		&i.FireAt,
		&i.RuntimeMcpOverlay,
		&i.InitiatorUserID,
		&i.OriginatorUserID,
		&i.AccountableUserID,
		&i.OriginatorSource,
		&i.TriggerCommentID,
		&i.CoalescedCommentIds,
		&i.DeliveredCommentIds,
		&i.ChatInputTaskID,
		&i.ChatFinalizeDeferredAt,
		&i.EscalationForTaskID,
		&i.DelegatedFromTaskID,
		&i.RetryOfTaskID,
		&i.RerunOfTaskID,
		&i.TriggerEvidenceKind,
		&i.TriggerEvidenceRefID,
		&i.SessionRolloutMissing,
		&i.RetiredSessionID,
		&i.DispatchedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.ToolBundleID,
	)
	return i, err
}

const deleteChatDraftRestore = `-- name: DeleteChatDraftRestore :execrows
DELETE FROM chat_draft_restore
WHERE id = $1 AND chat_session_id = $2
`

type DeleteChatDraftRestoreParams struct {
	ID            pgtype.UUID `json:"id"`
	ChatSessionID pgtype.UUID `json:"chat_session_id"`
}

func (q *Queries) DeleteChatDraftRestore(ctx context.Context, arg DeleteChatDraftRestoreParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChatDraftRestore, arg.ID, arg.ChatSessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteChatDraftRestoresBySession = `-- name: DeleteChatDraftRestoresBySession :execrows
DELETE FROM chat_draft_restore WHERE chat_session_id = $1
`

func (q *Queries) DeleteChatDraftRestoresBySession(ctx context.Context, chatSessionID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChatDraftRestoresBySession, chatSessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteChatMessagesBySession = `-- name: DeleteChatMessagesBySession :execrows
DELETE FROM chat_message WHERE chat_session_id = $1
`

func (q *Queries) DeleteChatMessagesBySession(ctx context.Context, chatSessionID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChatMessagesBySession, chatSessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteChatSession = `-- name: DeleteChatSession :execrows
DELETE FROM chat_session
WHERE id = $1 AND workspace_id = $2 AND status = 'archived'
`

type DeleteChatSessionParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteChatSession(ctx context.Context, arg DeleteChatSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChatSession, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTaskMessagesByChatSession = `-- name: DeleteTaskMessagesByChatSession :execrows
DELETE FROM task_message WHERE task_id IN (
    SELECT task.id FROM agent_task_queue task
    WHERE task.workspace_id = $1
      AND task.chat_session_id = $2
      AND task.status IN ('completed', 'failed', 'cancelled')
)
`

type DeleteTaskMessagesByChatSessionParams struct {
	TargetWorkspaceID   pgtype.UUID `json:"target_workspace_id"`
	TargetChatSessionID pgtype.UUID `json:"target_chat_session_id"`
}

func (q *Queries) DeleteTaskMessagesByChatSession(ctx context.Context, arg DeleteTaskMessagesByChatSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTaskMessagesByChatSession, arg.TargetWorkspaceID, arg.TargetChatSessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTaskTokensByChatSession = `-- name: DeleteTaskTokensByChatSession :execrows
DELETE FROM task_token WHERE task_id IN (
    SELECT task.id FROM agent_task_queue task
    WHERE task.workspace_id = $1
      AND task.chat_session_id = $2
      AND task.status IN ('completed', 'failed', 'cancelled')
)
`

type DeleteTaskTokensByChatSessionParams struct {
	TargetWorkspaceID   pgtype.UUID `json:"target_workspace_id"`
	TargetChatSessionID pgtype.UUID `json:"target_chat_session_id"`
}

func (q *Queries) DeleteTaskTokensByChatSession(ctx context.Context, arg DeleteTaskTokensByChatSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTaskTokensByChatSession, arg.TargetWorkspaceID, arg.TargetChatSessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTaskUsageByChatSession = `-- name: DeleteTaskUsageByChatSession :execrows
DELETE FROM task_usage WHERE task_id IN (
    SELECT task.id FROM agent_task_queue task
    WHERE task.workspace_id = $1
      AND task.chat_session_id = $2
      AND task.status IN ('completed', 'failed', 'cancelled')
)
`

type DeleteTaskUsageByChatSessionParams struct {
	TargetWorkspaceID   pgtype.UUID `json:"target_workspace_id"`
	TargetChatSessionID pgtype.UUID `json:"target_chat_session_id"`
}

func (q *Queries) DeleteTaskUsageByChatSession(ctx context.Context, arg DeleteTaskUsageByChatSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTaskUsageByChatSession, arg.TargetWorkspaceID, arg.TargetChatSessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTerminalTasksByChatSession = `-- name: DeleteTerminalTasksByChatSession :execrows
DELETE FROM agent_task_queue
WHERE workspace_id = $1
  AND chat_session_id = $2
  AND status IN ('completed', 'failed', 'cancelled')
`

type DeleteTerminalTasksByChatSessionParams struct {
	WorkspaceID   pgtype.UUID `json:"workspace_id"`
	ChatSessionID pgtype.UUID `json:"chat_session_id"`
}

func (q *Queries) DeleteTerminalTasksByChatSession(ctx context.Context, arg DeleteTerminalTasksByChatSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTerminalTasksByChatSession, arg.WorkspaceID, arg.ChatSessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getChatMessageByIdempotencyKey = `-- name: GetChatMessageByIdempotencyKey :one
SELECT id, chat_session_id, role, content, task_id, failure_reason, elapsed_ms, message_kind, idempotency_key, request_hash, created_at FROM chat_message
WHERE chat_session_id = $1
  AND idempotency_key = $2
`

type GetChatMessageByIdempotencyKeyParams struct {
	ChatSessionID  pgtype.UUID `json:"chat_session_id"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
}

func (q *Queries) GetChatMessageByIdempotencyKey(ctx context.Context, arg GetChatMessageByIdempotencyKeyParams) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, getChatMessageByIdempotencyKey, arg.ChatSessionID, arg.IdempotencyKey)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.ChatSessionID,
		&i.Role,
		&i.Content,
		&i.TaskID,
		&i.FailureReason,
		&i.ElapsedMs,
		&i.MessageKind,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.CreatedAt,
	)
	return i, err
}

const getChatMessageByTaskID = `-- name: GetChatMessageByTaskID :one
SELECT id, chat_session_id, role, content, task_id, failure_reason, elapsed_ms, message_kind, idempotency_key, request_hash, created_at FROM chat_message
WHERE chat_session_id = $1
  AND task_id = $2
  AND role = $3
ORDER BY created_at, id
LIMIT 1
`

type GetChatMessageByTaskIDParams struct {
	ChatSessionID pgtype.UUID `json:"chat_session_id"`
	TaskID        pgtype.UUID `json:"task_id"`
	Role          string      `json:"role"`
}

func (q *Queries) GetChatMessageByTaskID(ctx context.Context, arg GetChatMessageByTaskIDParams) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, getChatMessageByTaskID, arg.ChatSessionID, arg.TaskID, arg.Role)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.ChatSessionID,
		&i.Role,
		&i.Content,
		&i.TaskID,
		&i.FailureReason,
		&i.ElapsedMs,
		&i.MessageKind,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.CreatedAt,
	)
	return i, err
}

const getChatSession = `-- name: GetChatSession :one
SELECT id, workspace_id, agent_id, creator_id, runtime_id, title, session_id, work_dir, status, created_at, updated_at FROM chat_session
WHERE id = $1 AND workspace_id = $2
`

type GetChatSessionParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) GetChatSession(ctx context.Context, arg GetChatSessionParams) (ChatSession, error) {
	row := q.db.QueryRow(ctx, getChatSession, arg.ID, arg.WorkspaceID)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AgentID,
		&i.CreatorID,
		&i.RuntimeID,
		&i.Title,
		&i.SessionID,
		&i.WorkDir,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingChatTask = `-- name: GetPendingChatTask :one
SELECT id, workspace_id, agent_id, runtime_id, issue_id, chat_session_id, squad_id, is_leader_task, status, priority, attempt, max_attempts, parent_task_id, session_id, work_dir, context, result, error, failure_reason, trigger_summary, force_fresh_session, handoff_note, wait_reason, prepare_lease_expires_at, fire_at, runtime_mcp_overlay, initiator_user_id, originator_user_id, accountable_user_id, originator_source, trigger_comment_id, coalesced_comment_ids, delivered_comment_ids, chat_input_task_id, chat_finalize_deferred_at, escalation_for_task_id, delegated_from_task_id, retry_of_task_id, rerun_of_task_id, trigger_evidence_kind, trigger_evidence_ref_id, session_rollout_missing, retired_session_id, dispatched_at, started_at, completed_at, created_at, tool_bundle_id FROM agent_task_queue
WHERE workspace_id = $1
  AND chat_session_id = $2
  AND status IN ('deferred', 'queued', 'dispatched', 'waiting_local_directory', 'running')
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type GetPendingChatTaskParams struct {
	WorkspaceID   pgtype.UUID `json:"workspace_id"`
	ChatSessionID pgtype.UUID `json:"chat_session_id"`
}

func (q *Queries) GetPendingChatTask(ctx context.Context, arg GetPendingChatTaskParams) (AgentTaskQueue, error) {
	row := q.db.QueryRow(ctx, getPendingChatTask, arg.WorkspaceID, arg.ChatSessionID)
	var i AgentTaskQueue
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AgentID,
		&i.RuntimeID,
		&i.IssueID,
		&i.ChatSessionID,
		&i.SquadID,
		&i.IsLeaderTask,
		&i.Status,
		&i.Priority,
		&i.Attempt,
		&i.MaxAttempts,
		&i.ParentTaskID,
		&i.SessionID,
		&i.WorkDir,
		&i.Context,
		&i.Result,
		&i.Error,
		&i.FailureReason,
		&i.TriggerSummary,
		&i.ForceFreshSession,
		&i.HandoffNote,
		&i.WaitReason,
		&i.PrepareLeaseExpiresAt,
		&i.FireAt,
		&i.RuntimeMcpOverlay,
		&i.InitiatorUserID,
		&i.OriginatorUserID,
		&i.AccountableUserID,
		&i.OriginatorSource,
		&i.TriggerCommentID,
		&i.CoalescedCommentIds,
		&i.DeliveredCommentIds,
		&i.ChatInputTaskID,
		&i.ChatFinalizeDeferredAt,
		&i.EscalationForTaskID,
		&i.DelegatedFromTaskID,
		&i.RetryOfTaskID,
		&i.RerunOfTaskID,
		&i.TriggerEvidenceKind,
		&i.TriggerEvidenceRefID,
		&i.SessionRolloutMissing,
		&i.RetiredSessionID,
		&i.DispatchedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.ToolBundleID,
	)
	return i, err
}

const listAgentBuilderSessionsByCreator = `-- name: ListAgentBuilderSessionsByCreator :many
SELECT cs.id,
       cs.title,
       cs.created_at,
       cs.updated_at,
       a.runtime_id,
       COALESCE(lm.content, '') AS last_message_content,
       COALESCE(lm.role, '') AS last_message_role,
       lm.created_at AS last_message_at,
       d.draft AS stored_draft
FROM chat_session cs
JOIN agent a ON a.id = cs.agent_id
LEFT JOIN agent_builder_draft d ON d.chat_session_id = cs.id
LEFT JOIN LATERAL (
  SELECT content, role, created_at
    FROM chat_message m
   WHERE m.chat_session_id = cs.id
   ORDER BY m.created_at DESC
   LIMIT 1
) lm ON true
WHERE cs.workspace_id = $1
  AND cs.creator_id = $2
  AND cs.status = 'active'
  AND a.kind = 'system'
  AND a.system_key LIKE 'agent_builder:%'
  AND (lm.created_at IS NOT NULL OR d.chat_session_id IS NOT NULL)
ORDER BY COALESCE(lm.created_at, d.updated_at, cs.updated_at) DESC
`

type ListAgentBuilderSessionsByCreatorParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	CreatorID   pgtype.UUID `json:"creator_id"`
}

type ListAgentBuilderSessionsByCreatorRow struct {
	ID                 pgtype.UUID        `json:"id"`
	Title              string             `json:"title"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	RuntimeID          pgtype.UUID        `json:"runtime_id"`
	LastMessageContent string             `json:"last_message_content"`
	LastMessageRole    string             `json:"last_message_role"`
	LastMessageAt      pgtype.Timestamptz `json:"last_message_at"`
	StoredDraft        []byte             `json:"stored_draft"`
}

func (q *Queries) ListAgentBuilderSessionsByCreator(ctx context.Context, arg ListAgentBuilderSessionsByCreatorParams) ([]ListAgentBuilderSessionsByCreatorRow, error) {
	rows, err := q.db.Query(ctx, listAgentBuilderSessionsByCreator, arg.WorkspaceID, arg.CreatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentBuilderSessionsByCreatorRow{}
	for rows.Next() {
		var i ListAgentBuilderSessionsByCreatorRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RuntimeID,
			&i.LastMessageContent,
			&i.LastMessageRole,
			&i.LastMessageAt,
			&i.StoredDraft,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatDraftRestores = `-- name: ListChatDraftRestores :many
SELECT id, chat_session_id, task_id, content, created_at FROM chat_draft_restore
WHERE chat_session_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListChatDraftRestores(ctx context.Context, chatSessionID pgtype.UUID) ([]ChatDraftRestore, error) {
	rows, err := q.db.Query(ctx, listChatDraftRestores, chatSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatDraftRestore{}
	for rows.Next() {
		var i ChatDraftRestore
		if err := rows.Scan(
			&i.ID,
			&i.ChatSessionID,
			&i.TaskID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatMessagesPage = `-- name: ListChatMessagesPage :many
SELECT id, chat_session_id, role, content, task_id, failure_reason, elapsed_ms, message_kind, idempotency_key, request_hash, created_at FROM chat_message
WHERE chat_session_id = $1
  AND (
      $2::timestamptz IS NULL
      OR (created_at, id) > ($2::timestamptz, $3::uuid)
  )
ORDER BY created_at, id
LIMIT $4
`

type ListChatMessagesPageParams struct {
	ChatSessionID   pgtype.UUID        `json:"chat_session_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	PageLimit       int32              `json:"page_limit"`
}

func (q *Queries) ListChatMessagesPage(ctx context.Context, arg ListChatMessagesPageParams) ([]ChatMessage, error) {
	rows, err := q.db.Query(ctx, listChatMessagesPage,
		arg.ChatSessionID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatMessage{}
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.ChatSessionID,
			&i.Role,
			&i.Content,
			&i.TaskID,
			&i.FailureReason,
			&i.ElapsedMs,
			&i.MessageKind,
			&i.IdempotencyKey,
			&i.RequestHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatSessionsPage = `-- name: ListChatSessionsPage :many
SELECT id, workspace_id, agent_id, creator_id, runtime_id, title, session_id, work_dir, status, created_at, updated_at FROM chat_session
WHERE workspace_id = $1
  AND creator_id = $2
  AND (
      $3::timestamptz IS NULL
      OR (updated_at, id) < ($3::timestamptz, $4::uuid)
  )
ORDER BY updated_at DESC, id DESC
LIMIT $5
`

type ListChatSessionsPageParams struct {
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	CreatorID       pgtype.UUID        `json:"creator_id"`
	CursorUpdatedAt pgtype.Timestamptz `json:"cursor_updated_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	PageLimit       int32              `json:"page_limit"`
}

func (q *Queries) ListChatSessionsPage(ctx context.Context, arg ListChatSessionsPageParams) ([]ChatSession, error) {
	rows, err := q.db.Query(ctx, listChatSessionsPage,
		arg.WorkspaceID,
		arg.CreatorID,
		arg.CursorUpdatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatSession{}
	for rows.Next() {
		var i ChatSession
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AgentID,
			&i.CreatorID,
			&i.RuntimeID,
			&i.Title,
			&i.SessionID,
			&i.WorkDir,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockChatSession = `-- name: LockChatSession :one
SELECT id, workspace_id, agent_id, creator_id, runtime_id, title, session_id, work_dir, status, created_at, updated_at FROM chat_session
WHERE id = $1 AND workspace_id = $2
FOR UPDATE
`

type LockChatSessionParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) LockChatSession(ctx context.Context, arg LockChatSessionParams) (ChatSession, error) {
	row := q.db.QueryRow(ctx, lockChatSession, arg.ID, arg.WorkspaceID)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AgentID,
		&i.CreatorID,
		&i.RuntimeID,
		&i.Title,
		&i.SessionID,
		&i.WorkDir,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const rebindChatSessionRuntime = `-- name: RebindChatSessionRuntime :one
UPDATE chat_session
SET runtime_id = $1,
    session_id = CASE WHEN runtime_id = $1 THEN session_id ELSE NULL END,
    work_dir = CASE WHEN runtime_id = $1 THEN work_dir ELSE NULL END,
    updated_at = now()
WHERE id = $2 AND workspace_id = $3
RETURNING id, workspace_id, agent_id, creator_id, runtime_id, title, session_id, work_dir, status, created_at, updated_at
`

type RebindChatSessionRuntimeParams struct {
	RuntimeID   pgtype.UUID `json:"runtime_id"`
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) RebindChatSessionRuntime(ctx context.Context, arg RebindChatSessionRuntimeParams) (ChatSession, error) {
	row := q.db.QueryRow(ctx, rebindChatSessionRuntime, arg.RuntimeID, arg.ID, arg.WorkspaceID)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AgentID,
		&i.CreatorID,
		&i.RuntimeID,
		&i.Title,
		&i.SessionID,
		&i.WorkDir,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchChatSession = `-- name: TouchChatSession :one
UPDATE chat_session
SET updated_at = now()
WHERE id = $1 AND workspace_id = $2
RETURNING id, workspace_id, agent_id, creator_id, runtime_id, title, session_id, work_dir, status, created_at, updated_at
`

type TouchChatSessionParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) TouchChatSession(ctx context.Context, arg TouchChatSessionParams) (ChatSession, error) {
	row := q.db.QueryRow(ctx, touchChatSession, arg.ID, arg.WorkspaceID)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AgentID,
		&i.CreatorID,
		&i.RuntimeID,
		&i.Title,
		&i.SessionID,
		&i.WorkDir,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateChatSession = `-- name: UpdateChatSession :one
UPDATE chat_session
SET title = CASE WHEN $1::boolean THEN $2 ELSE title END,
    status = CASE WHEN $3::boolean THEN $4 ELSE status END,
    updated_at = now()
WHERE id = $5 AND workspace_id = $6
RETURNING id, workspace_id, agent_id, creator_id, runtime_id, title, session_id, work_dir, status, created_at, updated_at
`

type UpdateChatSessionParams struct {
	SetTitle    bool        `json:"set_title"`
	Title       string      `json:"title"`
	SetStatus   bool        `json:"set_status"`
	Status      string      `json:"status"`
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) UpdateChatSession(ctx context.Context, arg UpdateChatSessionParams) (ChatSession, error) {
	row := q.db.QueryRow(ctx, updateChatSession,
		arg.SetTitle,
		arg.Title,
		arg.SetStatus,
		arg.Status,
		arg.ID,
		arg.WorkspaceID,
	)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AgentID,
		&i.CreatorID,
		&i.RuntimeID,
		&i.Title,
		&i.SessionID,
		&i.WorkDir,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateChatSessionResume = `-- name: UpdateChatSessionResume :one
UPDATE chat_session
SET session_id = $1, work_dir = $2, updated_at = now()
WHERE id = $3 AND workspace_id = $4
RETURNING id, workspace_id, agent_id, creator_id, runtime_id, title, session_id, work_dir, status, created_at, updated_at
`

type UpdateChatSessionResumeParams struct {
	SessionID   pgtype.Text `json:"session_id"`
	WorkDir     pgtype.Text `json:"work_dir"`
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) UpdateChatSessionResume(ctx context.Context, arg UpdateChatSessionResumeParams) (ChatSession, error) {
	row := q.db.QueryRow(ctx, updateChatSessionResume,
		arg.SessionID,
		arg.WorkDir,
		arg.ID,
		arg.WorkspaceID,
	)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AgentID,
		&i.CreatorID,
		&i.RuntimeID,
		&i.Title,
		&i.SessionID,
		&i.WorkDir,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
