// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity_workspace_token.sql

package lightweightdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeVerificationCode = `-- name: ConsumeVerificationCode :execrows
UPDATE verification_code
SET used_at = now()
WHERE id = $1 AND used_at IS NULL AND attempts < 5 AND expires_at > now()
`

func (q *Queries) ConsumeVerificationCode(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, consumeVerificationCode, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createDaemonToken = `-- name: CreateDaemonToken :one
INSERT INTO daemon_token (token_hash, workspace_id, daemon_id, expires_at, user_id, name, token_prefix)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7
)
ON CONFLICT (workspace_id, daemon_id) DO UPDATE
SET token_hash = EXCLUDED.token_hash,
    expires_at = EXCLUDED.expires_at,
    user_id = EXCLUDED.user_id,
    name = EXCLUDED.name,
    token_prefix = EXCLUDED.token_prefix,
    created_at = now()
RETURNING id, token_hash, workspace_id, daemon_id, expires_at, created_at, user_id, name, token_prefix
`

type CreateDaemonTokenParams struct {
	TokenHash   string             `json:"token_hash"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	DaemonID    string             `json:"daemon_id"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	UserID      pgtype.UUID        `json:"user_id"`
	Name        pgtype.Text        `json:"name"`
	TokenPrefix pgtype.Text        `json:"token_prefix"`
}

func (q *Queries) CreateDaemonToken(ctx context.Context, arg CreateDaemonTokenParams) (DaemonToken, error) {
	row := q.db.QueryRow(ctx, createDaemonToken,
		arg.TokenHash,
		arg.WorkspaceID,
		arg.DaemonID,
		arg.ExpiresAt,
		arg.UserID,
		arg.Name,
		arg.TokenPrefix,
	)
	var i DaemonToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.WorkspaceID,
		&i.DaemonID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UserID,
		&i.Name,
		&i.TokenPrefix,
	)
	return i, err
}

const createMember = `-- name: CreateMember :one
INSERT INTO member (workspace_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING id, workspace_id, user_id, role, created_at
`

type CreateMemberParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
	Role        string      `json:"role"`
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, createMember, arg.WorkspaceID, arg.UserID, arg.Role)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const createPersonalAccessToken = `-- name: CreatePersonalAccessToken :one
INSERT INTO personal_access_token (user_id, name, token_hash, token_prefix, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, token_hash, token_prefix, expires_at, last_used_at, revoked, created_at
`

type CreatePersonalAccessTokenParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	Name        string             `json:"name"`
	TokenHash   string             `json:"token_hash"`
	TokenPrefix string             `json:"token_prefix"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreatePersonalAccessToken(ctx context.Context, arg CreatePersonalAccessTokenParams) (PersonalAccessToken, error) {
	row := q.db.QueryRow(ctx, createPersonalAccessToken,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.ExpiresAt,
	)
	var i PersonalAccessToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.Revoked,
		&i.CreatedAt,
	)
	return i, err
}

const createTaskToken = `-- name: CreateTaskToken :one
INSERT INTO task_token (token_hash, task_id, agent_id, workspace_id, user_id, tool_bundle_id, expires_at)
VALUES (
    $1, $2, $3,
    $4, $5, $6, $7
)
RETURNING id, token_hash, task_id, agent_id, workspace_id, user_id, expires_at, created_at, tool_bundle_id
`

type CreateTaskTokenParams struct {
	TokenHash    string             `json:"token_hash"`
	TaskID       pgtype.UUID        `json:"task_id"`
	AgentID      pgtype.UUID        `json:"agent_id"`
	WorkspaceID  pgtype.UUID        `json:"workspace_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	ToolBundleID pgtype.Text        `json:"tool_bundle_id"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateTaskToken(ctx context.Context, arg CreateTaskTokenParams) (TaskToken, error) {
	row := q.db.QueryRow(ctx, createTaskToken,
		arg.TokenHash,
		arg.TaskID,
		arg.AgentID,
		arg.WorkspaceID,
		arg.UserID,
		arg.ToolBundleID,
		arg.ExpiresAt,
	)
	var i TaskToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.TaskID,
		&i.AgentID,
		&i.WorkspaceID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.ToolBundleID,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO "user" (name, email, language, timezone)
VALUES ($1, $2, $3, $4)
RETURNING id, name, email, language, timezone, created_at, updated_at
`

type CreateUserParams struct {
	Name     string      `json:"name"`
	Email    string      `json:"email"`
	Language string      `json:"language"`
	Timezone pgtype.Text `json:"timezone"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Language,
		arg.Timezone,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Language,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVerificationCode = `-- name: CreateVerificationCode :one
INSERT INTO verification_code (email, code_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, email, code_hash, expires_at, used_at, attempts, created_at
`

type CreateVerificationCodeParams struct {
	Email     string             `json:"email"`
	CodeHash  string             `json:"code_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateVerificationCode(ctx context.Context, arg CreateVerificationCodeParams) (VerificationCode, error) {
	row := q.db.QueryRow(ctx, createVerificationCode, arg.Email, arg.CodeHash, arg.ExpiresAt)
	var i VerificationCode
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.Attempts,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspace (
    name, slug, description, context, settings, repos,
    issue_prefix, issue_counter, attribution_fail_closed
)
VALUES (
    $1, $2, $3, '', '{}'::jsonb, '[]'::jsonb,
    $4, 0, false
)
RETURNING id, name, slug, description, context, settings, repos, issue_prefix, issue_counter, attribution_fail_closed, created_at, updated_at
`

type CreateWorkspaceParams struct {
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description pgtype.Text `json:"description"`
	IssuePrefix string      `json:"issue_prefix"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.IssuePrefix,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Context,
		&i.Settings,
		&i.Repos,
		&i.IssuePrefix,
		&i.IssueCounter,
		&i.AttributionFailClosed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDaemonTokenByID = `-- name: DeleteDaemonTokenByID :one
DELETE FROM daemon_token
WHERE id = $1 AND workspace_id = $2
RETURNING id, token_hash, workspace_id, daemon_id, expires_at, created_at, user_id, name, token_prefix
`

type DeleteDaemonTokenByIDParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteDaemonTokenByID(ctx context.Context, arg DeleteDaemonTokenByIDParams) (DaemonToken, error) {
	row := q.db.QueryRow(ctx, deleteDaemonTokenByID, arg.ID, arg.WorkspaceID)
	var i DaemonToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.WorkspaceID,
		&i.DaemonID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UserID,
		&i.Name,
		&i.TokenPrefix,
	)
	return i, err
}

const deleteDaemonTokensByWorkspace = `-- name: DeleteDaemonTokensByWorkspace :execrows
DELETE FROM daemon_token WHERE workspace_id = $1
`

func (q *Queries) DeleteDaemonTokensByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDaemonTokensByWorkspace, workspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredDaemonTokens = `-- name: DeleteExpiredDaemonTokens :execrows
DELETE FROM daemon_token WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredDaemonTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredDaemonTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredTaskTokens = `-- name: DeleteExpiredTaskTokens :execrows
DELETE FROM task_token WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredTaskTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredTaskTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredVerificationCodes = `-- name: DeleteExpiredVerificationCodes :execrows
DELETE FROM verification_code
WHERE expires_at <= now() OR used_at IS NOT NULL OR attempts >= 5
`

func (q *Queries) DeleteExpiredVerificationCodes(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredVerificationCodes)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMembersByWorkspace = `-- name: DeleteMembersByWorkspace :execrows
DELETE FROM member WHERE workspace_id = $1
`

func (q *Queries) DeleteMembersByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMembersByWorkspace, workspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTaskTokensByTask = `-- name: DeleteTaskTokensByTask :execrows
DELETE FROM task_token WHERE task_id = $1
`

func (q *Queries) DeleteTaskTokensByTask(ctx context.Context, taskID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTaskTokensByTask, taskID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTaskTokensByWorkspace = `-- name: DeleteTaskTokensByWorkspace :execrows
DELETE FROM task_token WHERE workspace_id = $1
`

func (q *Queries) DeleteTaskTokensByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTaskTokensByWorkspace, workspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteWorkspace = `-- name: DeleteWorkspace :execrows
DELETE FROM workspace WHERE id = $1
`

func (q *Queries) DeleteWorkspace(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWorkspace, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDaemonTokenByHash = `-- name: GetDaemonTokenByHash :one
SELECT id, token_hash, workspace_id, daemon_id, expires_at, created_at, user_id, name, token_prefix FROM daemon_token
WHERE token_hash = $1 AND expires_at > now()
`

func (q *Queries) GetDaemonTokenByHash(ctx context.Context, tokenHash string) (DaemonToken, error) {
	row := q.db.QueryRow(ctx, getDaemonTokenByHash, tokenHash)
	var i DaemonToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.WorkspaceID,
		&i.DaemonID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UserID,
		&i.Name,
		&i.TokenPrefix,
	)
	return i, err
}

const getDaemonTokenByHashForUpdate = `-- name: GetDaemonTokenByHashForUpdate :one
SELECT id, token_hash, workspace_id, daemon_id, expires_at, created_at, user_id, name, token_prefix FROM daemon_token
WHERE token_hash = $1 AND expires_at > now()
FOR UPDATE
`

func (q *Queries) GetDaemonTokenByHashForUpdate(ctx context.Context, tokenHash string) (DaemonToken, error) {
	row := q.db.QueryRow(ctx, getDaemonTokenByHashForUpdate, tokenHash)
	var i DaemonToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.WorkspaceID,
		&i.DaemonID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UserID,
		&i.Name,
		&i.TokenPrefix,
	)
	return i, err
}

const getLatestUsableVerificationCode = `-- name: GetLatestUsableVerificationCode :one
SELECT id, email, code_hash, expires_at, used_at, attempts, created_at
FROM verification_code
WHERE email = $1
  AND used_at IS NULL
  AND attempts < 5
  AND expires_at > now()
ORDER BY created_at DESC
LIMIT 1
FOR UPDATE
`

func (q *Queries) GetLatestUsableVerificationCode(ctx context.Context, email string) (VerificationCode, error) {
	row := q.db.QueryRow(ctx, getLatestUsableVerificationCode, email)
	var i VerificationCode
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.Attempts,
		&i.CreatedAt,
	)
	return i, err
}

const getMember = `-- name: GetMember :one
SELECT id, workspace_id, user_id, role, created_at
FROM member
WHERE workspace_id = $1 AND user_id = $2
`

type GetMemberParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetMember(ctx context.Context, arg GetMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, getMember, arg.WorkspaceID, arg.UserID)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getMemberByID = `-- name: GetMemberByID :one
SELECT id, workspace_id, user_id, role, created_at FROM member
WHERE id = $1 AND workspace_id = $2
`

type GetMemberByIDParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) GetMemberByID(ctx context.Context, arg GetMemberByIDParams) (Member, error) {
	row := q.db.QueryRow(ctx, getMemberByID, arg.ID, arg.WorkspaceID)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getPersonalAccessTokenByHash = `-- name: GetPersonalAccessTokenByHash :one
SELECT id, user_id, name, token_hash, token_prefix, expires_at, last_used_at, revoked, created_at
FROM personal_access_token
WHERE token_hash = $1
  AND revoked = false
  AND (expires_at IS NULL OR expires_at > now())
`

func (q *Queries) GetPersonalAccessTokenByHash(ctx context.Context, tokenHash string) (PersonalAccessToken, error) {
	row := q.db.QueryRow(ctx, getPersonalAccessTokenByHash, tokenHash)
	var i PersonalAccessToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.Revoked,
		&i.CreatedAt,
	)
	return i, err
}

const getSchemaMetadata = `-- name: GetSchemaMetadata :one
SELECT id, edition, schema_version, installed_at, updated_at
FROM schema_metadata
WHERE id = 1
`

func (q *Queries) GetSchemaMetadata(ctx context.Context) (SchemaMetadatum, error) {
	row := q.db.QueryRow(ctx, getSchemaMetadata)
	var i SchemaMetadatum
	err := row.Scan(
		&i.ID,
		&i.Edition,
		&i.SchemaVersion,
		&i.InstalledAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskTokenByHash = `-- name: GetTaskTokenByHash :one
SELECT id, token_hash, task_id, agent_id, workspace_id, user_id, expires_at, created_at, tool_bundle_id FROM task_token
WHERE token_hash = $1 AND expires_at > now()
`

func (q *Queries) GetTaskTokenByHash(ctx context.Context, tokenHash string) (TaskToken, error) {
	row := q.db.QueryRow(ctx, getTaskTokenByHash, tokenHash)
	var i TaskToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.TaskID,
		&i.AgentID,
		&i.WorkspaceID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.ToolBundleID,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, language, timezone, created_at, updated_at FROM "user" WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Language,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, language, timezone, created_at, updated_at FROM "user" WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Language,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, name, slug, description, context, settings, repos, issue_prefix, issue_counter, attribution_fail_closed, created_at, updated_at FROM workspace WHERE id = $1
`

func (q *Queries) GetWorkspace(ctx context.Context, id pgtype.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Context,
		&i.Settings,
		&i.Repos,
		&i.IssuePrefix,
		&i.IssueCounter,
		&i.AttributionFailClosed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceBySlug = `-- name: GetWorkspaceBySlug :one
SELECT id, name, slug, description, context, settings, repos, issue_prefix, issue_counter, attribution_fail_closed, created_at, updated_at FROM workspace WHERE slug = $1
`

func (q *Queries) GetWorkspaceBySlug(ctx context.Context, slug string) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceBySlug, slug)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Context,
		&i.Settings,
		&i.Repos,
		&i.IssuePrefix,
		&i.IssueCounter,
		&i.AttributionFailClosed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementVerificationCodeAttempts = `-- name: IncrementVerificationCodeAttempts :one
UPDATE verification_code
SET attempts = attempts + 1
WHERE id = $1 AND used_at IS NULL AND attempts < 5
RETURNING attempts
`

func (q *Queries) IncrementVerificationCodeAttempts(ctx context.Context, id pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, incrementVerificationCodeAttempts, id)
	var attempts int32
	err := row.Scan(&attempts)
	return attempts, err
}

const listDaemonTokensByWorkspace = `-- name: ListDaemonTokensByWorkspace :many
SELECT id, token_hash, workspace_id, daemon_id, expires_at, created_at, user_id, name, token_prefix FROM daemon_token
WHERE workspace_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListDaemonTokensByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]DaemonToken, error) {
	rows, err := q.db.Query(ctx, listDaemonTokensByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DaemonToken{}
	for rows.Next() {
		var i DaemonToken
		if err := rows.Scan(
			&i.ID,
			&i.TokenHash,
			&i.WorkspaceID,
			&i.DaemonID,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UserID,
			&i.Name,
			&i.TokenPrefix,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonalAccessTokens = `-- name: ListPersonalAccessTokens :many
SELECT id, user_id, name, token_hash, token_prefix, expires_at, last_used_at, revoked, created_at FROM personal_access_token
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListPersonalAccessTokens(ctx context.Context, userID pgtype.UUID) ([]PersonalAccessToken, error) {
	rows, err := q.db.Query(ctx, listPersonalAccessTokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PersonalAccessToken{}
	for rows.Next() {
		var i PersonalAccessToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenHash,
			&i.TokenPrefix,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.Revoked,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceMembers = `-- name: ListWorkspaceMembers :many
SELECT m.id, m.workspace_id, m.user_id, m.role, m.created_at,
       u.name AS user_name, u.email AS user_email
FROM member m
JOIN "user" u ON u.id = m.user_id
WHERE m.workspace_id = $1
ORDER BY m.created_at, m.id
`

type ListWorkspaceMembersRow struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Role        string             `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UserName    string             `json:"user_name"`
	UserEmail   string             `json:"user_email"`
}

func (q *Queries) ListWorkspaceMembers(ctx context.Context, workspaceID pgtype.UUID) ([]ListWorkspaceMembersRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceMembers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceMembersRow{}
	for rows.Next() {
		var i ListWorkspaceMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.UserName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesForUser = `-- name: ListWorkspacesForUser :many
SELECT w.id, w.name, w.slug, w.description, w.context, w.settings, w.repos, w.issue_prefix, w.issue_counter, w.attribution_fail_closed, w.created_at, w.updated_at
FROM workspace w
JOIN member m ON m.workspace_id = w.id
WHERE m.user_id = $1
ORDER BY w.created_at, w.id
`

func (q *Queries) ListWorkspacesForUser(ctx context.Context, userID pgtype.UUID) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, listWorkspacesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Context,
			&i.Settings,
			&i.Repos,
			&i.IssuePrefix,
			&i.IssueCounter,
			&i.AttributionFailClosed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockWorkspaceIssueCounter = `-- name: LockWorkspaceIssueCounter :one
UPDATE workspace
SET issue_counter = issue_counter + 1,
    updated_at = now()
WHERE id = $1
RETURNING issue_counter, issue_prefix
`

type LockWorkspaceIssueCounterRow struct {
	IssueCounter int32  `json:"issue_counter"`
	IssuePrefix  string `json:"issue_prefix"`
}

func (q *Queries) LockWorkspaceIssueCounter(ctx context.Context, id pgtype.UUID) (LockWorkspaceIssueCounterRow, error) {
	row := q.db.QueryRow(ctx, lockWorkspaceIssueCounter, id)
	var i LockWorkspaceIssueCounterRow
	err := row.Scan(&i.IssueCounter, &i.IssuePrefix)
	return i, err
}

const renewPersonalAccessToken = `-- name: RenewPersonalAccessToken :one
UPDATE personal_access_token
SET token_hash = $1,
    token_prefix = $2,
    expires_at = $3,
    revoked = false
WHERE id = $4 AND user_id = $5 AND revoked = false
RETURNING id, user_id, name, token_hash, token_prefix, expires_at, last_used_at, revoked, created_at
`

type RenewPersonalAccessTokenParams struct {
	TokenHash   string             `json:"token_hash"`
	TokenPrefix string             `json:"token_prefix"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
}

func (q *Queries) RenewPersonalAccessToken(ctx context.Context, arg RenewPersonalAccessTokenParams) (PersonalAccessToken, error) {
	row := q.db.QueryRow(ctx, renewPersonalAccessToken,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.ExpiresAt,
		arg.ID,
		arg.UserID,
	)
	var i PersonalAccessToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.Revoked,
		&i.CreatedAt,
	)
	return i, err
}

const revokePersonalAccessToken = `-- name: RevokePersonalAccessToken :execrows
UPDATE personal_access_token
SET revoked = true
WHERE id = $1 AND user_id = $2 AND revoked = false
`

type RevokePersonalAccessTokenParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) RevokePersonalAccessToken(ctx context.Context, arg RevokePersonalAccessTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokePersonalAccessToken, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchPersonalAccessToken = `-- name: TouchPersonalAccessToken :execrows
UPDATE personal_access_token SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchPersonalAccessToken(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, touchPersonalAccessToken, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE "user"
SET name = CASE WHEN $1::boolean THEN $2 ELSE name END,
    language = CASE WHEN $3::boolean THEN $4 ELSE language END,
    timezone = CASE WHEN $5::boolean THEN $6::text ELSE timezone END,
    updated_at = now()
WHERE id = $7
RETURNING id, name, email, language, timezone, created_at, updated_at
`

type UpdateUserProfileParams struct {
	SetName     bool        `json:"set_name"`
	Name        string      `json:"name"`
	SetLanguage bool        `json:"set_language"`
	Language    string      `json:"language"`
	SetTimezone bool        `json:"set_timezone"`
	Timezone    pgtype.Text `json:"timezone"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.SetName,
		arg.Name,
		arg.SetLanguage,
		arg.Language,
		arg.SetTimezone,
		arg.Timezone,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Language,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWorkspace = `-- name: UpdateWorkspace :one
UPDATE workspace
SET name = CASE WHEN $1::boolean THEN $2 ELSE name END,
    description = CASE WHEN $3::boolean THEN $4::text ELSE description END,
    context = CASE WHEN $5::boolean THEN $6 ELSE context END,
    settings = CASE WHEN $7::boolean THEN $8::jsonb ELSE settings END,
    repos = CASE WHEN $9::boolean THEN $10::jsonb ELSE repos END,
    updated_at = now()
WHERE id = $11
RETURNING id, name, slug, description, context, settings, repos, issue_prefix, issue_counter, attribution_fail_closed, created_at, updated_at
`

type UpdateWorkspaceParams struct {
	SetName        bool        `json:"set_name"`
	Name           string      `json:"name"`
	SetDescription bool        `json:"set_description"`
	Description    pgtype.Text `json:"description"`
	SetContext     bool        `json:"set_context"`
	Context        string      `json:"context"`
	SetSettings    bool        `json:"set_settings"`
	Settings       []byte      `json:"settings"`
	SetRepos       bool        `json:"set_repos"`
	Repos          []byte      `json:"repos"`
	ID             pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, updateWorkspace,
		arg.SetName,
		arg.Name,
		arg.SetDescription,
		arg.Description,
		arg.SetContext,
		arg.Context,
		arg.SetSettings,
		arg.Settings,
		arg.SetRepos,
		arg.Repos,
		arg.ID,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Context,
		&i.Settings,
		&i.Repos,
		&i.IssuePrefix,
		&i.IssueCounter,
		&i.AttributionFailClosed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
