// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package lightweightdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ActivityLog struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	IssueID     pgtype.UUID        `json:"issue_id"`
	ActorType   string             `json:"actor_type"`
	ActorID     pgtype.UUID        `json:"actor_id"`
	Action      string             `json:"action"`
	Details     []byte             `json:"details"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Agent struct {
	ID                    pgtype.UUID        `json:"id"`
	WorkspaceID           pgtype.UUID        `json:"workspace_id"`
	RuntimeID             pgtype.UUID        `json:"runtime_id"`
	OwnerID               pgtype.UUID        `json:"owner_id"`
	Name                  string             `json:"name"`
	Description           string             `json:"description"`
	Instructions          string             `json:"instructions"`
	AvatarUrl             pgtype.Text        `json:"avatar_url"`
	RuntimeMode           string             `json:"runtime_mode"`
	RuntimeConfig         []byte             `json:"runtime_config"`
	Status                string             `json:"status"`
	MaxConcurrentTasks    int32              `json:"max_concurrent_tasks"`
	CustomEnv             []byte             `json:"custom_env"`
	CustomArgs            []byte             `json:"custom_args"`
	McpConfig             []byte             `json:"mcp_config"`
	Model                 pgtype.Text        `json:"model"`
	ThinkingLevel         pgtype.Text        `json:"thinking_level"`
	ServiceTier           pgtype.Text        `json:"service_tier"`
	PermissionMode        string             `json:"permission_mode"`
	DisabledRuntimeSkills []byte             `json:"disabled_runtime_skills"`
	ArchivedAt            pgtype.Timestamptz `json:"archived_at"`
	ArchivedBy            pgtype.UUID        `json:"archived_by"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	Kind                  string             `json:"kind"`
	SystemKey             pgtype.Text        `json:"system_key"`
}

type AgentBuilderDraft struct {
	ChatSessionID pgtype.UUID        `json:"chat_session_id"`
	WorkspaceID   pgtype.UUID        `json:"workspace_id"`
	Draft         []byte             `json:"draft"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type AgentInvocationTarget struct {
	ID         pgtype.UUID        `json:"id"`
	AgentID    pgtype.UUID        `json:"agent_id"`
	TargetType string             `json:"target_type"`
	TargetID   pgtype.UUID        `json:"target_id"`
	CreatedBy  pgtype.UUID        `json:"created_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AgentRuntime struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	DaemonID    string             `json:"daemon_id"`
	Name        string             `json:"name"`
	RuntimeMode string             `json:"runtime_mode"`
	Provider    string             `json:"provider"`
	Status      string             `json:"status"`
	DeviceInfo  string             `json:"device_info"`
	Metadata    []byte             `json:"metadata"`
	LastSeenAt  pgtype.Timestamptz `json:"last_seen_at"`
	OwnerID     pgtype.UUID        `json:"owner_id"`
	ProfileID   pgtype.UUID        `json:"profile_id"`
	CustomName  pgtype.Text        `json:"custom_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type AgentSkill struct {
	AgentID   pgtype.UUID        `json:"agent_id"`
	SkillID   pgtype.UUID        `json:"skill_id"`
	Enabled   bool               `json:"enabled"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AgentTaskQueue struct {
	ID                     pgtype.UUID        `json:"id"`
	WorkspaceID            pgtype.UUID        `json:"workspace_id"`
	AgentID                pgtype.UUID        `json:"agent_id"`
	RuntimeID              pgtype.UUID        `json:"runtime_id"`
	IssueID                pgtype.UUID        `json:"issue_id"`
	ChatSessionID          pgtype.UUID        `json:"chat_session_id"`
	SquadID                pgtype.UUID        `json:"squad_id"`
	IsLeaderTask           bool               `json:"is_leader_task"`
	Status                 string             `json:"status"`
	Priority               int32              `json:"priority"`
	Attempt                int32              `json:"attempt"`
	MaxAttempts            int32              `json:"max_attempts"`
	ParentTaskID           pgtype.UUID        `json:"parent_task_id"`
	SessionID              pgtype.Text        `json:"session_id"`
	WorkDir                pgtype.Text        `json:"work_dir"`
	Context                []byte             `json:"context"`
	Result                 []byte             `json:"result"`
	Error                  pgtype.Text        `json:"error"`
	FailureReason          pgtype.Text        `json:"failure_reason"`
	TriggerSummary         pgtype.Text        `json:"trigger_summary"`
	ForceFreshSession      bool               `json:"force_fresh_session"`
	HandoffNote            pgtype.Text        `json:"handoff_note"`
	WaitReason             pgtype.Text        `json:"wait_reason"`
	PrepareLeaseExpiresAt  pgtype.Timestamptz `json:"prepare_lease_expires_at"`
	FireAt                 pgtype.Timestamptz `json:"fire_at"`
	RuntimeMcpOverlay      []byte             `json:"runtime_mcp_overlay"`
	InitiatorUserID        pgtype.UUID        `json:"initiator_user_id"`
	OriginatorUserID       pgtype.UUID        `json:"originator_user_id"`
	AccountableUserID      pgtype.UUID        `json:"accountable_user_id"`
	OriginatorSource       pgtype.Text        `json:"originator_source"`
	TriggerCommentID       pgtype.UUID        `json:"trigger_comment_id"`
	CoalescedCommentIds    []pgtype.UUID      `json:"coalesced_comment_ids"`
	DeliveredCommentIds    []pgtype.UUID      `json:"delivered_comment_ids"`
	ChatInputTaskID        pgtype.UUID        `json:"chat_input_task_id"`
	ChatFinalizeDeferredAt pgtype.Timestamptz `json:"chat_finalize_deferred_at"`
	EscalationForTaskID    pgtype.UUID        `json:"escalation_for_task_id"`
	DelegatedFromTaskID    pgtype.UUID        `json:"delegated_from_task_id"`
	RetryOfTaskID          pgtype.UUID        `json:"retry_of_task_id"`
	RerunOfTaskID          pgtype.UUID        `json:"rerun_of_task_id"`
	TriggerEvidenceKind    pgtype.Text        `json:"trigger_evidence_kind"`
	TriggerEvidenceRefID   pgtype.UUID        `json:"trigger_evidence_ref_id"`
	SessionRolloutMissing  bool               `json:"session_rollout_missing"`
	RetiredSessionID       pgtype.Text        `json:"retired_session_id"`
	DispatchedAt           pgtype.Timestamptz `json:"dispatched_at"`
	StartedAt              pgtype.Timestamptz `json:"started_at"`
	CompletedAt            pgtype.Timestamptz `json:"completed_at"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	ToolBundleID           pgtype.Text        `json:"tool_bundle_id"`
}

type AgentToolBundleHead struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	AgentID     pgtype.UUID        `json:"agent_id"`
	BundleID    string             `json:"bundle_id"`
	UpdatedBy   pgtype.UUID        `json:"updated_by"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ChatDraftRestore struct {
	ID            pgtype.UUID        `json:"id"`
	ChatSessionID pgtype.UUID        `json:"chat_session_id"`
	TaskID        pgtype.UUID        `json:"task_id"`
	Content       string             `json:"content"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type ChatMessage struct {
	ID             pgtype.UUID        `json:"id"`
	ChatSessionID  pgtype.UUID        `json:"chat_session_id"`
	Role           string             `json:"role"`
	Content        string             `json:"content"`
	TaskID         pgtype.UUID        `json:"task_id"`
	FailureReason  pgtype.Text        `json:"failure_reason"`
	ElapsedMs      pgtype.Int8        `json:"elapsed_ms"`
	MessageKind    string             `json:"message_kind"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	RequestHash    pgtype.Text        `json:"request_hash"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ChatSession struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	AgentID     pgtype.UUID        `json:"agent_id"`
	CreatorID   pgtype.UUID        `json:"creator_id"`
	RuntimeID   pgtype.UUID        `json:"runtime_id"`
	Title       string             `json:"title"`
	SessionID   pgtype.Text        `json:"session_id"`
	WorkDir     pgtype.Text        `json:"work_dir"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Comment struct {
	ID             pgtype.UUID        `json:"id"`
	WorkspaceID    pgtype.UUID        `json:"workspace_id"`
	IssueID        pgtype.UUID        `json:"issue_id"`
	AuthorType     string             `json:"author_type"`
	AuthorID       pgtype.UUID        `json:"author_id"`
	Content        string             `json:"content"`
	Type           string             `json:"type"`
	SourceTaskID   pgtype.UUID        `json:"source_task_id"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	RequestHash    pgtype.Text        `json:"request_hash"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type DaemonToken struct {
	ID          pgtype.UUID        `json:"id"`
	TokenHash   string             `json:"token_hash"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	DaemonID    string             `json:"daemon_id"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UserID      pgtype.UUID        `json:"user_id"`
	Name        pgtype.Text        `json:"name"`
	TokenPrefix pgtype.Text        `json:"token_prefix"`
}

type Issue struct {
	ID                 pgtype.UUID        `json:"id"`
	WorkspaceID        pgtype.UUID        `json:"workspace_id"`
	Title              string             `json:"title"`
	Description        string             `json:"description"`
	Status             string             `json:"status"`
	AssigneeType       string             `json:"assignee_type"`
	AssigneeID         pgtype.UUID        `json:"assignee_id"`
	CreatorType        string             `json:"creator_type"`
	CreatorID          pgtype.UUID        `json:"creator_id"`
	AcceptanceCriteria []byte             `json:"acceptance_criteria"`
	ContextRefs        []byte             `json:"context_refs"`
	Number             int32              `json:"number"`
	IdempotencyKey     pgtype.Text        `json:"idempotency_key"`
	RequestHash        pgtype.Text        `json:"request_hash"`
	FirstExecutedAt    pgtype.Timestamptz `json:"first_executed_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Member struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Role        string             `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type PersonalAccessToken struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Name        string             `json:"name"`
	TokenHash   string             `json:"token_hash"`
	TokenPrefix string             `json:"token_prefix"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	Revoked     bool               `json:"revoked"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type RuntimeProfile struct {
	ID             pgtype.UUID        `json:"id"`
	WorkspaceID    pgtype.UUID        `json:"workspace_id"`
	DisplayName    string             `json:"display_name"`
	ProtocolFamily string             `json:"protocol_family"`
	CommandName    string             `json:"command_name"`
	Description    pgtype.Text        `json:"description"`
	FixedArgs      []byte             `json:"fixed_args"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	Enabled        bool               `json:"enabled"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type SchemaMetadatum struct {
	ID            int16              `json:"id"`
	Edition       string             `json:"edition"`
	SchemaVersion int32              `json:"schema_version"`
	InstalledAt   pgtype.Timestamptz `json:"installed_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Skill struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Content     string             `json:"content"`
	Config      []byte             `json:"config"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type SkillFile struct {
	ID        pgtype.UUID        `json:"id"`
	SkillID   pgtype.UUID        `json:"skill_id"`
	Path      string             `json:"path"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Squad struct {
	ID           pgtype.UUID        `json:"id"`
	WorkspaceID  pgtype.UUID        `json:"workspace_id"`
	Name         string             `json:"name"`
	Description  string             `json:"description"`
	Instructions string             `json:"instructions"`
	LeaderID     pgtype.UUID        `json:"leader_id"`
	CreatorID    pgtype.UUID        `json:"creator_id"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	ArchivedAt   pgtype.Timestamptz `json:"archived_at"`
	ArchivedBy   pgtype.UUID        `json:"archived_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type SquadMember struct {
	ID        pgtype.UUID        `json:"id"`
	SquadID   pgtype.UUID        `json:"squad_id"`
	AgentID   pgtype.UUID        `json:"agent_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type TaskMessage struct {
	ID        pgtype.UUID        `json:"id"`
	TaskID    pgtype.UUID        `json:"task_id"`
	Seq       int32              `json:"seq"`
	Type      string             `json:"type"`
	Tool      pgtype.Text        `json:"tool"`
	Content   pgtype.Text        `json:"content"`
	Input     []byte             `json:"input"`
	Output    pgtype.Text        `json:"output"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type TaskToken struct {
	ID           pgtype.UUID        `json:"id"`
	TokenHash    string             `json:"token_hash"`
	TaskID       pgtype.UUID        `json:"task_id"`
	AgentID      pgtype.UUID        `json:"agent_id"`
	WorkspaceID  pgtype.UUID        `json:"workspace_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ToolBundleID pgtype.Text        `json:"tool_bundle_id"`
}

type TaskUsage struct {
	ID               pgtype.UUID        `json:"id"`
	TaskID           pgtype.UUID        `json:"task_id"`
	Provider         string             `json:"provider"`
	Model            string             `json:"model"`
	InputTokens      int64              `json:"input_tokens"`
	OutputTokens     int64              `json:"output_tokens"`
	CacheReadTokens  int64              `json:"cache_read_tokens"`
	CacheWriteTokens int64              `json:"cache_write_tokens"`
	CostUsdTicks     pgtype.Int8        `json:"cost_usd_ticks"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type ToolBundle struct {
	ID           string             `json:"id"`
	WorkspaceID  pgtype.UUID        `json:"workspace_id"`
	ManifestHash string             `json:"manifest_hash"`
	Status       string             `json:"status"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
}

type ToolBundleItem struct {
	ID                 pgtype.UUID        `json:"id"`
	WorkspaceID        pgtype.UUID        `json:"workspace_id"`
	BundleID           string             `json:"bundle_id"`
	Ordinal            int32              `json:"ordinal"`
	PublicName         string             `json:"public_name"`
	SourceID           pgtype.UUID        `json:"source_id"`
	SourceRevisionID   pgtype.UUID        `json:"source_revision_id"`
	ToolDefinitionID   pgtype.UUID        `json:"tool_definition_id"`
	ArtifactID         pgtype.UUID        `json:"artifact_id"`
	DefinitionSnapshot []byte             `json:"definition_snapshot"`
	InvocationPlan     []byte             `json:"invocation_plan"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type ToolDefinition struct {
	ID                pgtype.UUID        `json:"id"`
	WorkspaceID       pgtype.UUID        `json:"workspace_id"`
	SourceID          pgtype.UUID        `json:"source_id"`
	SourceRevisionID  pgtype.UUID        `json:"source_revision_id"`
	PublicName        string             `json:"public_name"`
	UpstreamName      string             `json:"upstream_name"`
	Description       string             `json:"description"`
	InputSchema       []byte             `json:"input_schema"`
	OutputSchema      []byte             `json:"output_schema"`
	OperationMetadata []byte             `json:"operation_metadata"`
	Enabled           bool               `json:"enabled"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type ToolSource struct {
	ID              pgtype.UUID        `json:"id"`
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	Name            string             `json:"name"`
	Kind            string             `json:"kind"`
	Enabled         bool               `json:"enabled"`
	CurrentRevision pgtype.UUID        `json:"current_revision"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type ToolSourceArtifact struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	SourceID    pgtype.UUID        `json:"source_id"`
	Sha256      string             `json:"sha256"`
	MediaType   string             `json:"media_type"`
	SizeBytes   int64              `json:"size_bytes"`
	Content     []byte             `json:"content"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ToolSourceRevision struct {
	ID              pgtype.UUID        `json:"id"`
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	SourceID        pgtype.UUID        `json:"source_id"`
	Revision        int32              `json:"revision"`
	Status          string             `json:"status"`
	Endpoint        pgtype.Text        `json:"endpoint"`
	TransportConfig []byte             `json:"transport_config"`
	ArtifactID      pgtype.UUID        `json:"artifact_id"`
	SecretID        pgtype.UUID        `json:"secret_id"`
	ValidationCode  pgtype.Text        `json:"validation_code"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
}

type ToolSourceSecret struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	SourceID    pgtype.UUID        `json:"source_id"`
	Envelope    []byte             `json:"envelope"`
	KeyID       string             `json:"key_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Email     string             `json:"email"`
	Language  string             `json:"language"`
	Timezone  pgtype.Text        `json:"timezone"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type VerificationCode struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	CodeHash  string             `json:"code_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	Attempts  int32              `json:"attempts"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Workspace struct {
	ID                    pgtype.UUID        `json:"id"`
	Name                  string             `json:"name"`
	Slug                  string             `json:"slug"`
	Description           pgtype.Text        `json:"description"`
	Context               string             `json:"context"`
	Settings              []byte             `json:"settings"`
	Repos                 []byte             `json:"repos"`
	IssuePrefix           string             `json:"issue_prefix"`
	IssueCounter          int32              `json:"issue_counter"`
	AttributionFailClosed bool               `json:"attribution_fail_closed"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}
