// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runtime_agent_skill.sql

package lightweightdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveAgent = `-- name: ArchiveAgent :one
UPDATE agent
SET archived_at = now(), archived_by = $1, updated_at = now()
WHERE id = $2 AND workspace_id = $3 AND archived_at IS NULL
RETURNING id, workspace_id, runtime_id, owner_id, name, description, instructions, avatar_url, runtime_mode, runtime_config, status, max_concurrent_tasks, custom_env, custom_args, mcp_config, model, thinking_level, service_tier, permission_mode, disabled_runtime_skills, archived_at, archived_by, created_at, updated_at, kind, system_key
`

type ArchiveAgentParams struct {
	ActorID     pgtype.UUID `json:"actor_id"`
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) ArchiveAgent(ctx context.Context, arg ArchiveAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, archiveAgent, arg.ActorID, arg.ID, arg.WorkspaceID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RuntimeID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Instructions,
		&i.AvatarUrl,
		&i.RuntimeMode,
		&i.RuntimeConfig,
		&i.Status,
		&i.MaxConcurrentTasks,
		&i.CustomEnv,
		&i.CustomArgs,
		&i.McpConfig,
		&i.Model,
		&i.ThinkingLevel,
		&i.ServiceTier,
		&i.PermissionMode,
		&i.DisabledRuntimeSkills,
		&i.ArchivedAt,
		&i.ArchivedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
		&i.SystemKey,
	)
	return i, err
}

const clearAgentRuntimeBindings = `-- name: ClearAgentRuntimeBindings :execrows
UPDATE agent SET runtime_id = NULL, updated_at = now()
WHERE workspace_id = $1 AND runtime_id = $2
`

type ClearAgentRuntimeBindingsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	RuntimeID   pgtype.UUID `json:"runtime_id"`
}

func (q *Queries) ClearAgentRuntimeBindings(ctx context.Context, arg ClearAgentRuntimeBindingsParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearAgentRuntimeBindings, arg.WorkspaceID, arg.RuntimeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countActiveTasksByAgent = `-- name: CountActiveTasksByAgent :one
SELECT count(*) FROM agent_task_queue
WHERE workspace_id = $1 AND agent_id = $2
  AND status IN ('deferred', 'queued', 'dispatched', 'waiting_local_directory', 'running')
`

type CountActiveTasksByAgentParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	AgentID     pgtype.UUID `json:"agent_id"`
}

func (q *Queries) CountActiveTasksByAgent(ctx context.Context, arg CountActiveTasksByAgentParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveTasksByAgent, arg.WorkspaceID, arg.AgentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveTasksByRuntime = `-- name: CountActiveTasksByRuntime :one
SELECT count(*) FROM agent_task_queue
WHERE workspace_id = $1 AND runtime_id = $2
  AND status IN ('deferred', 'queued', 'dispatched', 'waiting_local_directory', 'running')
`

type CountActiveTasksByRuntimeParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	RuntimeID   pgtype.UUID `json:"runtime_id"`
}

func (q *Queries) CountActiveTasksByRuntime(ctx context.Context, arg CountActiveTasksByRuntimeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveTasksByRuntime, arg.WorkspaceID, arg.RuntimeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAgentRuntimesByProfile = `-- name: CountAgentRuntimesByProfile :one
SELECT count(*) FROM agent_runtime
WHERE workspace_id = $1 AND profile_id = $2
`

type CountAgentRuntimesByProfileParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ProfileID   pgtype.UUID `json:"profile_id"`
}

func (q *Queries) CountAgentRuntimesByProfile(ctx context.Context, arg CountAgentRuntimesByProfileParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAgentRuntimesByProfile, arg.WorkspaceID, arg.ProfileID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAgentSkillBindings = `-- name: CountAgentSkillBindings :one
SELECT count(*) FROM agent_skill WHERE skill_id = $1
`

func (q *Queries) CountAgentSkillBindings(ctx context.Context, skillID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAgentSkillBindings, skillID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAgent = `-- name: CreateAgent :one
INSERT INTO agent (
    workspace_id, runtime_id, owner_id, name, description, instructions,
    runtime_config, max_concurrent_tasks, custom_env, custom_args, mcp_config,
    model, thinking_level, service_tier, permission_mode, disabled_runtime_skills,
    kind
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10,
    $11, $12, $13,
    $14, $15, $16,
    'user'
)
RETURNING id, workspace_id, runtime_id, owner_id, name, description, instructions, avatar_url, runtime_mode, runtime_config, status, max_concurrent_tasks, custom_env, custom_args, mcp_config, model, thinking_level, service_tier, permission_mode, disabled_runtime_skills, archived_at, archived_by, created_at, updated_at, kind, system_key
`

type CreateAgentParams struct {
	WorkspaceID           pgtype.UUID `json:"workspace_id"`
	RuntimeID             pgtype.UUID `json:"runtime_id"`
	OwnerID               pgtype.UUID `json:"owner_id"`
	Name                  string      `json:"name"`
	Description           string      `json:"description"`
	Instructions          string      `json:"instructions"`
	RuntimeConfig         []byte      `json:"runtime_config"`
	MaxConcurrentTasks    int32       `json:"max_concurrent_tasks"`
	CustomEnv             []byte      `json:"custom_env"`
	CustomArgs            []byte      `json:"custom_args"`
	McpConfig             []byte      `json:"mcp_config"`
	Model                 pgtype.Text `json:"model"`
	ThinkingLevel         pgtype.Text `json:"thinking_level"`
	ServiceTier           pgtype.Text `json:"service_tier"`
	PermissionMode        string      `json:"permission_mode"`
	DisabledRuntimeSkills []byte      `json:"disabled_runtime_skills"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, createAgent,
		arg.WorkspaceID,
		arg.RuntimeID,
		arg.OwnerID,
		arg.Name,
		arg.Description,
		arg.Instructions,
		arg.RuntimeConfig,
		arg.MaxConcurrentTasks,
		arg.CustomEnv,
		arg.CustomArgs,
		arg.McpConfig,
		arg.Model,
		arg.ThinkingLevel,
		arg.ServiceTier,
		arg.PermissionMode,
		arg.DisabledRuntimeSkills,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RuntimeID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Instructions,
		&i.AvatarUrl,
		&i.RuntimeMode,
		&i.RuntimeConfig,
		&i.Status,
		&i.MaxConcurrentTasks,
		&i.CustomEnv,
		&i.CustomArgs,
		&i.McpConfig,
		&i.Model,
		&i.ThinkingLevel,
		&i.ServiceTier,
		&i.PermissionMode,
		&i.DisabledRuntimeSkills,
		&i.ArchivedAt,
		&i.ArchivedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
		&i.SystemKey,
	)
	return i, err
}

const createAgentInvocationTarget = `-- name: CreateAgentInvocationTarget :one
INSERT INTO agent_invocation_target (agent_id, target_type, target_id, created_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (agent_id, target_type, target_id) DO UPDATE
SET created_by = EXCLUDED.created_by
RETURNING id, agent_id, target_type, target_id, created_by, created_at
`

type CreateAgentInvocationTargetParams struct {
	AgentID    pgtype.UUID `json:"agent_id"`
	TargetType string      `json:"target_type"`
	TargetID   pgtype.UUID `json:"target_id"`
	CreatedBy  pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateAgentInvocationTarget(ctx context.Context, arg CreateAgentInvocationTargetParams) (AgentInvocationTarget, error) {
	row := q.db.QueryRow(ctx, createAgentInvocationTarget,
		arg.AgentID,
		arg.TargetType,
		arg.TargetID,
		arg.CreatedBy,
	)
	var i AgentInvocationTarget
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.TargetType,
		&i.TargetID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createRuntimeProfile = `-- name: CreateRuntimeProfile :one
INSERT INTO runtime_profile (
    workspace_id, display_name, protocol_family, command_name,
    description, fixed_args, created_by, enabled
)
VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8
)
RETURNING id, workspace_id, display_name, protocol_family, command_name, description, fixed_args, created_by, enabled, created_at, updated_at
`

type CreateRuntimeProfileParams struct {
	WorkspaceID    pgtype.UUID `json:"workspace_id"`
	DisplayName    string      `json:"display_name"`
	ProtocolFamily string      `json:"protocol_family"`
	CommandName    string      `json:"command_name"`
	Description    pgtype.Text `json:"description"`
	FixedArgs      []byte      `json:"fixed_args"`
	CreatedBy      pgtype.UUID `json:"created_by"`
	Enabled        bool        `json:"enabled"`
}

func (q *Queries) CreateRuntimeProfile(ctx context.Context, arg CreateRuntimeProfileParams) (RuntimeProfile, error) {
	row := q.db.QueryRow(ctx, createRuntimeProfile,
		arg.WorkspaceID,
		arg.DisplayName,
		arg.ProtocolFamily,
		arg.CommandName,
		arg.Description,
		arg.FixedArgs,
		arg.CreatedBy,
		arg.Enabled,
	)
	var i RuntimeProfile
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DisplayName,
		&i.ProtocolFamily,
		&i.CommandName,
		&i.Description,
		&i.FixedArgs,
		&i.CreatedBy,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSkill = `-- name: CreateSkill :one
INSERT INTO skill (workspace_id, name, description, content, config, created_by)
VALUES (
    $1, $2, $3,
    $4, $5, $6
)
RETURNING id, workspace_id, name, description, content, config, created_by, created_at, updated_at
`

type CreateSkillParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Content     string      `json:"content"`
	Config      []byte      `json:"config"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateSkill(ctx context.Context, arg CreateSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, createSkill,
		arg.WorkspaceID,
		arg.Name,
		arg.Description,
		arg.Content,
		arg.Config,
		arg.CreatedBy,
	)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Content,
		&i.Config,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAgentInvocationTargets = `-- name: DeleteAgentInvocationTargets :execrows
DELETE FROM agent_invocation_target WHERE agent_id = $1
`

func (q *Queries) DeleteAgentInvocationTargets(ctx context.Context, agentID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAgentInvocationTargets, agentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAgentRuntime = `-- name: DeleteAgentRuntime :execrows
DELETE FROM agent_runtime
WHERE id = $1 AND workspace_id = $2
`

type DeleteAgentRuntimeParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteAgentRuntime(ctx context.Context, arg DeleteAgentRuntimeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAgentRuntime, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAgentSkills = `-- name: DeleteAgentSkills :execrows
DELETE FROM agent_skill WHERE agent_id = $1
`

func (q *Queries) DeleteAgentSkills(ctx context.Context, agentID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAgentSkills, agentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRuntimeProfile = `-- name: DeleteRuntimeProfile :execrows
DELETE FROM runtime_profile
WHERE id = $1 AND workspace_id = $2
`

type DeleteRuntimeProfileParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteRuntimeProfile(ctx context.Context, arg DeleteRuntimeProfileParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRuntimeProfile, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSkill = `-- name: DeleteSkill :execrows
DELETE FROM skill WHERE id = $1 AND workspace_id = $2
`

type DeleteSkillParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteSkill(ctx context.Context, arg DeleteSkillParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSkill, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSkillFile = `-- name: DeleteSkillFile :execrows
DELETE FROM skill_file WHERE id = $1 AND skill_id = $2
`

type DeleteSkillFileParams struct {
	ID      pgtype.UUID `json:"id"`
	SkillID pgtype.UUID `json:"skill_id"`
}

func (q *Queries) DeleteSkillFile(ctx context.Context, arg DeleteSkillFileParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSkillFile, arg.ID, arg.SkillID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSkillFilesBySkill = `-- name: DeleteSkillFilesBySkill :execrows
DELETE FROM skill_file WHERE skill_id = $1
`

func (q *Queries) DeleteSkillFilesBySkill(ctx context.Context, skillID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSkillFilesBySkill, skillID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAgent = `-- name: GetAgent :one
SELECT id, workspace_id, runtime_id, owner_id, name, description, instructions, avatar_url, runtime_mode, runtime_config, status, max_concurrent_tasks, custom_env, custom_args, mcp_config, model, thinking_level, service_tier, permission_mode, disabled_runtime_skills, archived_at, archived_by, created_at, updated_at, kind, system_key FROM agent
WHERE id = $1 AND workspace_id = $2 AND kind = 'user'
`

type GetAgentParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) GetAgent(ctx context.Context, arg GetAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgent, arg.ID, arg.WorkspaceID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RuntimeID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Instructions,
		&i.AvatarUrl,
		&i.RuntimeMode,
		&i.RuntimeConfig,
		&i.Status,
		&i.MaxConcurrentTasks,
		&i.CustomEnv,
		&i.CustomArgs,
		&i.McpConfig,
		&i.Model,
		&i.ThinkingLevel,
		&i.ServiceTier,
		&i.PermissionMode,
		&i.DisabledRuntimeSkills,
		&i.ArchivedAt,
		&i.ArchivedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
		&i.SystemKey,
	)
	return i, err
}

const getAgentRow = `-- name: GetAgentRow :one
SELECT id, workspace_id, runtime_id, owner_id, name, description, instructions, avatar_url, runtime_mode, runtime_config, status, max_concurrent_tasks, custom_env, custom_args, mcp_config, model, thinking_level, service_tier, permission_mode, disabled_runtime_skills, archived_at, archived_by, created_at, updated_at, kind, system_key FROM agent
WHERE id = $1 AND workspace_id = $2
`

type GetAgentRowParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) GetAgentRow(ctx context.Context, arg GetAgentRowParams) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentRow, arg.ID, arg.WorkspaceID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RuntimeID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Instructions,
		&i.AvatarUrl,
		&i.RuntimeMode,
		&i.RuntimeConfig,
		&i.Status,
		&i.MaxConcurrentTasks,
		&i.CustomEnv,
		&i.CustomArgs,
		&i.McpConfig,
		&i.Model,
		&i.ThinkingLevel,
		&i.ServiceTier,
		&i.PermissionMode,
		&i.DisabledRuntimeSkills,
		&i.ArchivedAt,
		&i.ArchivedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
		&i.SystemKey,
	)
	return i, err
}

const getAgentRuntime = `-- name: GetAgentRuntime :one
SELECT id, workspace_id, daemon_id, name, runtime_mode, provider, status, device_info, metadata, last_seen_at, owner_id, profile_id, custom_name, created_at, updated_at FROM agent_runtime
WHERE id = $1 AND workspace_id = $2
`

type GetAgentRuntimeParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) GetAgentRuntime(ctx context.Context, arg GetAgentRuntimeParams) (AgentRuntime, error) {
	row := q.db.QueryRow(ctx, getAgentRuntime, arg.ID, arg.WorkspaceID)
	var i AgentRuntime
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DaemonID,
		&i.Name,
		&i.RuntimeMode,
		&i.Provider,
		&i.Status,
		&i.DeviceInfo,
		&i.Metadata,
		&i.LastSeenAt,
		&i.OwnerID,
		&i.ProfileID,
		&i.CustomName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRuntimeProfile = `-- name: GetRuntimeProfile :one
SELECT id, workspace_id, display_name, protocol_family, command_name, description, fixed_args, created_by, enabled, created_at, updated_at FROM runtime_profile
WHERE id = $1 AND workspace_id = $2
`

type GetRuntimeProfileParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) GetRuntimeProfile(ctx context.Context, arg GetRuntimeProfileParams) (RuntimeProfile, error) {
	row := q.db.QueryRow(ctx, getRuntimeProfile, arg.ID, arg.WorkspaceID)
	var i RuntimeProfile
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DisplayName,
		&i.ProtocolFamily,
		&i.CommandName,
		&i.Description,
		&i.FixedArgs,
		&i.CreatedBy,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSkill = `-- name: GetSkill :one
SELECT id, workspace_id, name, description, content, config, created_by, created_at, updated_at FROM skill WHERE id = $1 AND workspace_id = $2
`

type GetSkillParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) GetSkill(ctx context.Context, arg GetSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, getSkill, arg.ID, arg.WorkspaceID)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Content,
		&i.Config,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSkillByWorkspaceAndName = `-- name: GetSkillByWorkspaceAndName :one
SELECT id, workspace_id, name, description, content, config, created_by, created_at, updated_at FROM skill
WHERE workspace_id = $1 AND name = $2
LIMIT 1
`

type GetSkillByWorkspaceAndNameParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Name        string      `json:"name"`
}

func (q *Queries) GetSkillByWorkspaceAndName(ctx context.Context, arg GetSkillByWorkspaceAndNameParams) (Skill, error) {
	row := q.db.QueryRow(ctx, getSkillByWorkspaceAndName, arg.WorkspaceID, arg.Name)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Content,
		&i.Config,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentInvocationTargets = `-- name: ListAgentInvocationTargets :many
SELECT id, agent_id, target_type, target_id, created_by, created_at FROM agent_invocation_target
WHERE agent_id = $1
ORDER BY target_type, target_id
`

func (q *Queries) ListAgentInvocationTargets(ctx context.Context, agentID pgtype.UUID) ([]AgentInvocationTarget, error) {
	rows, err := q.db.Query(ctx, listAgentInvocationTargets, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentInvocationTarget{}
	for rows.Next() {
		var i AgentInvocationTarget
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.TargetType,
			&i.TargetID,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentRuntimes = `-- name: ListAgentRuntimes :many
SELECT id, workspace_id, daemon_id, name, runtime_mode, provider, status, device_info, metadata, last_seen_at, owner_id, profile_id, custom_name, created_at, updated_at FROM agent_runtime
WHERE workspace_id = $1
ORDER BY status DESC, updated_at DESC, id DESC
`

func (q *Queries) ListAgentRuntimes(ctx context.Context, workspaceID pgtype.UUID) ([]AgentRuntime, error) {
	rows, err := q.db.Query(ctx, listAgentRuntimes, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentRuntime{}
	for rows.Next() {
		var i AgentRuntime
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.DaemonID,
			&i.Name,
			&i.RuntimeMode,
			&i.Provider,
			&i.Status,
			&i.DeviceInfo,
			&i.Metadata,
			&i.LastSeenAt,
			&i.OwnerID,
			&i.ProfileID,
			&i.CustomName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentRuntimesByDaemon = `-- name: ListAgentRuntimesByDaemon :many
SELECT id, workspace_id, daemon_id, name, runtime_mode, provider, status, device_info, metadata, last_seen_at, owner_id, profile_id, custom_name, created_at, updated_at FROM agent_runtime
WHERE workspace_id = $1 AND daemon_id = $2
ORDER BY provider, id
`

type ListAgentRuntimesByDaemonParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	DaemonID    string      `json:"daemon_id"`
}

func (q *Queries) ListAgentRuntimesByDaemon(ctx context.Context, arg ListAgentRuntimesByDaemonParams) ([]AgentRuntime, error) {
	rows, err := q.db.Query(ctx, listAgentRuntimesByDaemon, arg.WorkspaceID, arg.DaemonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentRuntime{}
	for rows.Next() {
		var i AgentRuntime
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.DaemonID,
			&i.Name,
			&i.RuntimeMode,
			&i.Provider,
			&i.Status,
			&i.DeviceInfo,
			&i.Metadata,
			&i.LastSeenAt,
			&i.OwnerID,
			&i.ProfileID,
			&i.CustomName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentSkills = `-- name: ListAgentSkills :many
SELECT s.id, s.workspace_id, s.name, s.description, s.content, s.config, s.created_by, s.created_at, s.updated_at, a_s.enabled
FROM agent_skill a_s
JOIN skill s ON s.id = a_s.skill_id
WHERE a_s.agent_id = $1
ORDER BY s.name, s.id
`

type ListAgentSkillsRow struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Content     string             `json:"content"`
	Config      []byte             `json:"config"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Enabled     bool               `json:"enabled"`
}

func (q *Queries) ListAgentSkills(ctx context.Context, agentID pgtype.UUID) ([]ListAgentSkillsRow, error) {
	rows, err := q.db.Query(ctx, listAgentSkills, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentSkillsRow{}
	for rows.Next() {
		var i ListAgentSkillsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Description,
			&i.Content,
			&i.Config,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgents = `-- name: ListAgents :many
SELECT id, workspace_id, runtime_id, owner_id, name, description, instructions, avatar_url, runtime_mode, runtime_config, status, max_concurrent_tasks, custom_env, custom_args, mcp_config, model, thinking_level, service_tier, permission_mode, disabled_runtime_skills, archived_at, archived_by, created_at, updated_at, kind, system_key FROM agent
WHERE workspace_id = $1 AND kind = 'user'
ORDER BY archived_at NULLS FIRST, updated_at DESC, id DESC
`

func (q *Queries) ListAgents(ctx context.Context, workspaceID pgtype.UUID) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgents, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.RuntimeID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Instructions,
			&i.AvatarUrl,
			&i.RuntimeMode,
			&i.RuntimeConfig,
			&i.Status,
			&i.MaxConcurrentTasks,
			&i.CustomEnv,
			&i.CustomArgs,
			&i.McpConfig,
			&i.Model,
			&i.ThinkingLevel,
			&i.ServiceTier,
			&i.PermissionMode,
			&i.DisabledRuntimeSkills,
			&i.ArchivedAt,
			&i.ArchivedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Kind,
			&i.SystemKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuntimeProfiles = `-- name: ListRuntimeProfiles :many
SELECT id, workspace_id, display_name, protocol_family, command_name, description, fixed_args, created_by, enabled, created_at, updated_at FROM runtime_profile
WHERE workspace_id = $1
ORDER BY enabled DESC, display_name, id
`

func (q *Queries) ListRuntimeProfiles(ctx context.Context, workspaceID pgtype.UUID) ([]RuntimeProfile, error) {
	rows, err := q.db.Query(ctx, listRuntimeProfiles, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RuntimeProfile{}
	for rows.Next() {
		var i RuntimeProfile
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.DisplayName,
			&i.ProtocolFamily,
			&i.CommandName,
			&i.Description,
			&i.FixedArgs,
			&i.CreatedBy,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillFiles = `-- name: ListSkillFiles :many
SELECT id, skill_id, path, content, created_at, updated_at FROM skill_file WHERE skill_id = $1 ORDER BY path, id
`

func (q *Queries) ListSkillFiles(ctx context.Context, skillID pgtype.UUID) ([]SkillFile, error) {
	rows, err := q.db.Query(ctx, listSkillFiles, skillID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SkillFile{}
	for rows.Next() {
		var i SkillFile
		if err := rows.Scan(
			&i.ID,
			&i.SkillID,
			&i.Path,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkills = `-- name: ListSkills :many
SELECT id, workspace_id, name, description, content, config, created_by, created_at, updated_at FROM skill
WHERE workspace_id = $1
ORDER BY updated_at DESC, id DESC
`

func (q *Queries) ListSkills(ctx context.Context, workspaceID pgtype.UUID) ([]Skill, error) {
	rows, err := q.db.Query(ctx, listSkills, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Skill{}
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Description,
			&i.Content,
			&i.Config,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleAgentRuntimes = `-- name: ListStaleAgentRuntimes :many
SELECT id, workspace_id, daemon_id, name, runtime_mode, provider, status, device_info, metadata, last_seen_at, owner_id, profile_id, custom_name, created_at, updated_at FROM agent_runtime
WHERE status = 'online' AND (last_seen_at IS NULL OR last_seen_at < $1)
ORDER BY last_seen_at NULLS FIRST, id
LIMIT $2
`

type ListStaleAgentRuntimesParams struct {
	StaleBefore pgtype.Timestamptz `json:"stale_before"`
	BatchLimit  int32              `json:"batch_limit"`
}

func (q *Queries) ListStaleAgentRuntimes(ctx context.Context, arg ListStaleAgentRuntimesParams) ([]AgentRuntime, error) {
	rows, err := q.db.Query(ctx, listStaleAgentRuntimes, arg.StaleBefore, arg.BatchLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentRuntime{}
	for rows.Next() {
		var i AgentRuntime
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.DaemonID,
			&i.Name,
			&i.RuntimeMode,
			&i.Provider,
			&i.Status,
			&i.DeviceInfo,
			&i.Metadata,
			&i.LastSeenAt,
			&i.OwnerID,
			&i.ProfileID,
			&i.CustomName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAgent = `-- name: LockAgent :one
SELECT id, workspace_id, runtime_id, owner_id, name, description, instructions, avatar_url, runtime_mode, runtime_config, status, max_concurrent_tasks, custom_env, custom_args, mcp_config, model, thinking_level, service_tier, permission_mode, disabled_runtime_skills, archived_at, archived_by, created_at, updated_at, kind, system_key FROM agent
WHERE id = $1 AND workspace_id = $2 AND kind = 'user'
FOR UPDATE
`

type LockAgentParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) LockAgent(ctx context.Context, arg LockAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, lockAgent, arg.ID, arg.WorkspaceID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RuntimeID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Instructions,
		&i.AvatarUrl,
		&i.RuntimeMode,
		&i.RuntimeConfig,
		&i.Status,
		&i.MaxConcurrentTasks,
		&i.CustomEnv,
		&i.CustomArgs,
		&i.McpConfig,
		&i.Model,
		&i.ThinkingLevel,
		&i.ServiceTier,
		&i.PermissionMode,
		&i.DisabledRuntimeSkills,
		&i.ArchivedAt,
		&i.ArchivedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
		&i.SystemKey,
	)
	return i, err
}

const lockAgentRuntime = `-- name: LockAgentRuntime :one
SELECT id, workspace_id, daemon_id, name, runtime_mode, provider, status, device_info, metadata, last_seen_at, owner_id, profile_id, custom_name, created_at, updated_at FROM agent_runtime
WHERE id = $1 AND workspace_id = $2
FOR UPDATE
`

type LockAgentRuntimeParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) LockAgentRuntime(ctx context.Context, arg LockAgentRuntimeParams) (AgentRuntime, error) {
	row := q.db.QueryRow(ctx, lockAgentRuntime, arg.ID, arg.WorkspaceID)
	var i AgentRuntime
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DaemonID,
		&i.Name,
		&i.RuntimeMode,
		&i.Provider,
		&i.Status,
		&i.DeviceInfo,
		&i.Metadata,
		&i.LastSeenAt,
		&i.OwnerID,
		&i.ProfileID,
		&i.CustomName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockAgentsByRuntime = `-- name: LockAgentsByRuntime :many
SELECT id, workspace_id, runtime_id, owner_id, name, description, instructions, avatar_url, runtime_mode, runtime_config, status, max_concurrent_tasks, custom_env, custom_args, mcp_config, model, thinking_level, service_tier, permission_mode, disabled_runtime_skills, archived_at, archived_by, created_at, updated_at, kind, system_key FROM agent
WHERE workspace_id = $1 AND runtime_id = $2
ORDER BY id
FOR UPDATE
`

type LockAgentsByRuntimeParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	RuntimeID   pgtype.UUID `json:"runtime_id"`
}

func (q *Queries) LockAgentsByRuntime(ctx context.Context, arg LockAgentsByRuntimeParams) ([]Agent, error) {
	rows, err := q.db.Query(ctx, lockAgentsByRuntime, arg.WorkspaceID, arg.RuntimeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.RuntimeID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Instructions,
			&i.AvatarUrl,
			&i.RuntimeMode,
			&i.RuntimeConfig,
			&i.Status,
			&i.MaxConcurrentTasks,
			&i.CustomEnv,
			&i.CustomArgs,
			&i.McpConfig,
			&i.Model,
			&i.ThinkingLevel,
			&i.ServiceTier,
			&i.PermissionMode,
			&i.DisabledRuntimeSkills,
			&i.ArchivedAt,
			&i.ArchivedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Kind,
			&i.SystemKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSkill = `-- name: LockSkill :one
SELECT id, workspace_id, name, description, content, config, created_by, created_at, updated_at FROM skill
WHERE id = $1 AND workspace_id = $2
FOR UPDATE
`

type LockSkillParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) LockSkill(ctx context.Context, arg LockSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, lockSkill, arg.ID, arg.WorkspaceID)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Content,
		&i.Config,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markAgentRuntimeOffline = `-- name: MarkAgentRuntimeOffline :one
UPDATE agent_runtime
SET status = 'offline', updated_at = now()
WHERE id = $1 AND workspace_id = $2 AND status = 'online'
  AND (last_seen_at IS NULL OR last_seen_at < $3)
RETURNING id, workspace_id, daemon_id, name, runtime_mode, provider, status, device_info, metadata, last_seen_at, owner_id, profile_id, custom_name, created_at, updated_at
`

type MarkAgentRuntimeOfflineParams struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	StaleBefore pgtype.Timestamptz `json:"stale_before"`
}

func (q *Queries) MarkAgentRuntimeOffline(ctx context.Context, arg MarkAgentRuntimeOfflineParams) (AgentRuntime, error) {
	row := q.db.QueryRow(ctx, markAgentRuntimeOffline, arg.ID, arg.WorkspaceID, arg.StaleBefore)
	var i AgentRuntime
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DaemonID,
		&i.Name,
		&i.RuntimeMode,
		&i.Provider,
		&i.Status,
		&i.DeviceInfo,
		&i.Metadata,
		&i.LastSeenAt,
		&i.OwnerID,
		&i.ProfileID,
		&i.CustomName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markAgentRuntimesOffline = `-- name: MarkAgentRuntimesOffline :many
UPDATE agent_runtime
SET status = 'offline', updated_at = now()
WHERE workspace_id = $1
  AND daemon_id = $2
RETURNING id, workspace_id, daemon_id, name, runtime_mode, provider, status, device_info, metadata, last_seen_at, owner_id, profile_id, custom_name, created_at, updated_at
`

type MarkAgentRuntimesOfflineParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	DaemonID    string      `json:"daemon_id"`
}

func (q *Queries) MarkAgentRuntimesOffline(ctx context.Context, arg MarkAgentRuntimesOfflineParams) ([]AgentRuntime, error) {
	rows, err := q.db.Query(ctx, markAgentRuntimesOffline, arg.WorkspaceID, arg.DaemonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentRuntime{}
	for rows.Next() {
		var i AgentRuntime
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.DaemonID,
			&i.Name,
			&i.RuntimeMode,
			&i.Provider,
			&i.Status,
			&i.DeviceInfo,
			&i.Metadata,
			&i.LastSeenAt,
			&i.OwnerID,
			&i.ProfileID,
			&i.CustomName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceAgentSkill = `-- name: ReplaceAgentSkill :one
INSERT INTO agent_skill (agent_id, skill_id, enabled)
VALUES ($1, $2, $3)
ON CONFLICT (agent_id, skill_id) DO UPDATE SET enabled = EXCLUDED.enabled
RETURNING agent_id, skill_id, enabled, created_at
`

type ReplaceAgentSkillParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	SkillID pgtype.UUID `json:"skill_id"`
	Enabled bool        `json:"enabled"`
}

func (q *Queries) ReplaceAgentSkill(ctx context.Context, arg ReplaceAgentSkillParams) (AgentSkill, error) {
	row := q.db.QueryRow(ctx, replaceAgentSkill, arg.AgentID, arg.SkillID, arg.Enabled)
	var i AgentSkill
	err := row.Scan(
		&i.AgentID,
		&i.SkillID,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const restoreAgent = `-- name: RestoreAgent :one
UPDATE agent
SET archived_at = NULL, archived_by = NULL, updated_at = now()
WHERE id = $1 AND workspace_id = $2 AND archived_at IS NOT NULL
RETURNING id, workspace_id, runtime_id, owner_id, name, description, instructions, avatar_url, runtime_mode, runtime_config, status, max_concurrent_tasks, custom_env, custom_args, mcp_config, model, thinking_level, service_tier, permission_mode, disabled_runtime_skills, archived_at, archived_by, created_at, updated_at, kind, system_key
`

type RestoreAgentParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) RestoreAgent(ctx context.Context, arg RestoreAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, restoreAgent, arg.ID, arg.WorkspaceID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RuntimeID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Instructions,
		&i.AvatarUrl,
		&i.RuntimeMode,
		&i.RuntimeConfig,
		&i.Status,
		&i.MaxConcurrentTasks,
		&i.CustomEnv,
		&i.CustomArgs,
		&i.McpConfig,
		&i.Model,
		&i.ThinkingLevel,
		&i.ServiceTier,
		&i.PermissionMode,
		&i.DisabledRuntimeSkills,
		&i.ArchivedAt,
		&i.ArchivedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
		&i.SystemKey,
	)
	return i, err
}

const touchAgentRuntime = `-- name: TouchAgentRuntime :execrows
UPDATE agent_runtime
SET status = 'online', last_seen_at = now(), updated_at = now()
WHERE id = $1 AND workspace_id = $2 AND daemon_id = $3
`

type TouchAgentRuntimeParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	DaemonID    string      `json:"daemon_id"`
}

func (q *Queries) TouchAgentRuntime(ctx context.Context, arg TouchAgentRuntimeParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchAgentRuntime, arg.ID, arg.WorkspaceID, arg.DaemonID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAgentRuntimesBatch = `-- name: TouchAgentRuntimesBatch :execrows
UPDATE agent_runtime
SET status = 'online', last_seen_at = now(), updated_at = now()
WHERE id = ANY($1::uuid[])
`

func (q *Queries) TouchAgentRuntimesBatch(ctx context.Context, runtimeIds []pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, touchAgentRuntimesBatch, runtimeIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAgent = `-- name: UpdateAgent :one
UPDATE agent
SET name = CASE WHEN $1::boolean THEN $2 ELSE name END,
    description = CASE WHEN $3::boolean THEN $4 ELSE description END,
    instructions = CASE WHEN $5::boolean THEN $6 ELSE instructions END,
    runtime_id = CASE WHEN $7::boolean THEN $8::uuid ELSE runtime_id END,
    runtime_config = CASE WHEN $9::boolean THEN $10::jsonb ELSE runtime_config END,
    custom_args = CASE WHEN $11::boolean THEN $12::jsonb ELSE custom_args END,
    mcp_config = CASE WHEN $13::boolean THEN $14::jsonb ELSE mcp_config END,
    model = CASE WHEN $15::boolean THEN $16::text ELSE model END,
    thinking_level = CASE WHEN $17::boolean THEN $18::text ELSE thinking_level END,
    service_tier = CASE WHEN $19::boolean THEN $20::text ELSE service_tier END,
    max_concurrent_tasks = CASE WHEN $21::boolean THEN $22 ELSE max_concurrent_tasks END,
    permission_mode = CASE WHEN $23::boolean THEN $24 ELSE permission_mode END,
    disabled_runtime_skills = CASE WHEN $25::boolean THEN $26::jsonb ELSE disabled_runtime_skills END,
    updated_at = now()
WHERE id = $27 AND workspace_id = $28
RETURNING id, workspace_id, runtime_id, owner_id, name, description, instructions, avatar_url, runtime_mode, runtime_config, status, max_concurrent_tasks, custom_env, custom_args, mcp_config, model, thinking_level, service_tier, permission_mode, disabled_runtime_skills, archived_at, archived_by, created_at, updated_at, kind, system_key
`

type UpdateAgentParams struct {
	SetName                  bool        `json:"set_name"`
	Name                     string      `json:"name"`
	SetDescription           bool        `json:"set_description"`
	Description              string      `json:"description"`
	SetInstructions          bool        `json:"set_instructions"`
	Instructions             string      `json:"instructions"`
	SetRuntimeID             bool        `json:"set_runtime_id"`
	RuntimeID                pgtype.UUID `json:"runtime_id"`
	SetRuntimeConfig         bool        `json:"set_runtime_config"`
	RuntimeConfig            []byte      `json:"runtime_config"`
	SetCustomArgs            bool        `json:"set_custom_args"`
	CustomArgs               []byte      `json:"custom_args"`
	SetMcpConfig             bool        `json:"set_mcp_config"`
	McpConfig                []byte      `json:"mcp_config"`
	SetModel                 bool        `json:"set_model"`
	Model                    pgtype.Text `json:"model"`
	SetThinkingLevel         bool        `json:"set_thinking_level"`
	ThinkingLevel            pgtype.Text `json:"thinking_level"`
	SetServiceTier           bool        `json:"set_service_tier"`
	ServiceTier              pgtype.Text `json:"service_tier"`
	SetMaxConcurrentTasks    bool        `json:"set_max_concurrent_tasks"`
	MaxConcurrentTasks       int32       `json:"max_concurrent_tasks"`
	SetPermissionMode        bool        `json:"set_permission_mode"`
	PermissionMode           string      `json:"permission_mode"`
	SetDisabledRuntimeSkills bool        `json:"set_disabled_runtime_skills"`
	DisabledRuntimeSkills    []byte      `json:"disabled_runtime_skills"`
	ID                       pgtype.UUID `json:"id"`
	WorkspaceID              pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) UpdateAgent(ctx context.Context, arg UpdateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, updateAgent,
		arg.SetName,
		arg.Name,
		arg.SetDescription,
		arg.Description,
		arg.SetInstructions,
		arg.Instructions,
		arg.SetRuntimeID,
		arg.RuntimeID,
		arg.SetRuntimeConfig,
		arg.RuntimeConfig,
		arg.SetCustomArgs,
		arg.CustomArgs,
		arg.SetMcpConfig,
		arg.McpConfig,
		arg.SetModel,
		arg.Model,
		arg.SetThinkingLevel,
		arg.ThinkingLevel,
		arg.SetServiceTier,
		arg.ServiceTier,
		arg.SetMaxConcurrentTasks,
		arg.MaxConcurrentTasks,
		arg.SetPermissionMode,
		arg.PermissionMode,
		arg.SetDisabledRuntimeSkills,
		arg.DisabledRuntimeSkills,
		arg.ID,
		arg.WorkspaceID,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RuntimeID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Instructions,
		&i.AvatarUrl,
		&i.RuntimeMode,
		&i.RuntimeConfig,
		&i.Status,
		&i.MaxConcurrentTasks,
		&i.CustomEnv,
		&i.CustomArgs,
		&i.McpConfig,
		&i.Model,
		&i.ThinkingLevel,
		&i.ServiceTier,
		&i.PermissionMode,
		&i.DisabledRuntimeSkills,
		&i.ArchivedAt,
		&i.ArchivedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
		&i.SystemKey,
	)
	return i, err
}

const updateAgentCustomEnv = `-- name: UpdateAgentCustomEnv :one
UPDATE agent
SET custom_env = $1, updated_at = now()
WHERE id = $2 AND workspace_id = $3
RETURNING id, workspace_id, runtime_id, owner_id, name, description, instructions, avatar_url, runtime_mode, runtime_config, status, max_concurrent_tasks, custom_env, custom_args, mcp_config, model, thinking_level, service_tier, permission_mode, disabled_runtime_skills, archived_at, archived_by, created_at, updated_at, kind, system_key
`

type UpdateAgentCustomEnvParams struct {
	CustomEnv   []byte      `json:"custom_env"`
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) UpdateAgentCustomEnv(ctx context.Context, arg UpdateAgentCustomEnvParams) (Agent, error) {
	row := q.db.QueryRow(ctx, updateAgentCustomEnv, arg.CustomEnv, arg.ID, arg.WorkspaceID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RuntimeID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Instructions,
		&i.AvatarUrl,
		&i.RuntimeMode,
		&i.RuntimeConfig,
		&i.Status,
		&i.MaxConcurrentTasks,
		&i.CustomEnv,
		&i.CustomArgs,
		&i.McpConfig,
		&i.Model,
		&i.ThinkingLevel,
		&i.ServiceTier,
		&i.PermissionMode,
		&i.DisabledRuntimeSkills,
		&i.ArchivedAt,
		&i.ArchivedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
		&i.SystemKey,
	)
	return i, err
}

const updateAgentRuntimeCustomName = `-- name: UpdateAgentRuntimeCustomName :one
UPDATE agent_runtime
SET custom_name = $1, updated_at = now()
WHERE id = $2 AND workspace_id = $3
RETURNING id, workspace_id, daemon_id, name, runtime_mode, provider, status, device_info, metadata, last_seen_at, owner_id, profile_id, custom_name, created_at, updated_at
`

type UpdateAgentRuntimeCustomNameParams struct {
	CustomName  pgtype.Text `json:"custom_name"`
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) UpdateAgentRuntimeCustomName(ctx context.Context, arg UpdateAgentRuntimeCustomNameParams) (AgentRuntime, error) {
	row := q.db.QueryRow(ctx, updateAgentRuntimeCustomName, arg.CustomName, arg.ID, arg.WorkspaceID)
	var i AgentRuntime
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DaemonID,
		&i.Name,
		&i.RuntimeMode,
		&i.Provider,
		&i.Status,
		&i.DeviceInfo,
		&i.Metadata,
		&i.LastSeenAt,
		&i.OwnerID,
		&i.ProfileID,
		&i.CustomName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRuntimeProfile = `-- name: UpdateRuntimeProfile :one
UPDATE runtime_profile
SET display_name = CASE WHEN $1::boolean THEN $2 ELSE display_name END,
    protocol_family = CASE WHEN $3::boolean THEN $4 ELSE protocol_family END,
    command_name = CASE WHEN $5::boolean THEN $6 ELSE command_name END,
    description = CASE WHEN $7::boolean THEN $8::text ELSE description END,
    fixed_args = CASE WHEN $9::boolean THEN $10::jsonb ELSE fixed_args END,
    enabled = CASE WHEN $11::boolean THEN $12 ELSE enabled END,
    updated_at = now()
WHERE id = $13 AND workspace_id = $14
RETURNING id, workspace_id, display_name, protocol_family, command_name, description, fixed_args, created_by, enabled, created_at, updated_at
`

type UpdateRuntimeProfileParams struct {
	SetDisplayName    bool        `json:"set_display_name"`
	DisplayName       string      `json:"display_name"`
	SetProtocolFamily bool        `json:"set_protocol_family"`
	ProtocolFamily    string      `json:"protocol_family"`
	SetCommandName    bool        `json:"set_command_name"`
	CommandName       string      `json:"command_name"`
	SetDescription    bool        `json:"set_description"`
	Description       pgtype.Text `json:"description"`
	SetFixedArgs      bool        `json:"set_fixed_args"`
	FixedArgs         []byte      `json:"fixed_args"`
	SetEnabled        bool        `json:"set_enabled"`
	Enabled           bool        `json:"enabled"`
	ID                pgtype.UUID `json:"id"`
	WorkspaceID       pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) UpdateRuntimeProfile(ctx context.Context, arg UpdateRuntimeProfileParams) (RuntimeProfile, error) {
	row := q.db.QueryRow(ctx, updateRuntimeProfile,
		arg.SetDisplayName,
		arg.DisplayName,
		arg.SetProtocolFamily,
		arg.ProtocolFamily,
		arg.SetCommandName,
		arg.CommandName,
		arg.SetDescription,
		arg.Description,
		arg.SetFixedArgs,
		arg.FixedArgs,
		arg.SetEnabled,
		arg.Enabled,
		arg.ID,
		arg.WorkspaceID,
	)
	var i RuntimeProfile
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DisplayName,
		&i.ProtocolFamily,
		&i.CommandName,
		&i.Description,
		&i.FixedArgs,
		&i.CreatedBy,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSkill = `-- name: UpdateSkill :one
UPDATE skill
SET name = CASE WHEN $1::boolean THEN $2 ELSE name END,
    description = CASE WHEN $3::boolean THEN $4 ELSE description END,
    content = CASE WHEN $5::boolean THEN $6 ELSE content END,
    config = CASE WHEN $7::boolean THEN $8::jsonb ELSE config END,
    updated_at = now()
WHERE id = $9 AND workspace_id = $10
RETURNING id, workspace_id, name, description, content, config, created_by, created_at, updated_at
`

type UpdateSkillParams struct {
	SetName        bool        `json:"set_name"`
	Name           string      `json:"name"`
	SetDescription bool        `json:"set_description"`
	Description    string      `json:"description"`
	SetContent     bool        `json:"set_content"`
	Content        string      `json:"content"`
	SetConfig      bool        `json:"set_config"`
	Config         []byte      `json:"config"`
	ID             pgtype.UUID `json:"id"`
	WorkspaceID    pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) UpdateSkill(ctx context.Context, arg UpdateSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, updateSkill,
		arg.SetName,
		arg.Name,
		arg.SetDescription,
		arg.Description,
		arg.SetContent,
		arg.Content,
		arg.SetConfig,
		arg.Config,
		arg.ID,
		arg.WorkspaceID,
	)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Content,
		&i.Config,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAgentRuntime = `-- name: UpsertAgentRuntime :one
INSERT INTO agent_runtime (
    workspace_id, daemon_id, name, provider, status, device_info,
    metadata, last_seen_at, owner_id, profile_id
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, now(),
    $8, $9
)
ON CONFLICT (workspace_id, daemon_id, provider, profile_id)
DO UPDATE SET name = EXCLUDED.name,
              status = EXCLUDED.status,
              device_info = EXCLUDED.device_info,
              metadata = EXCLUDED.metadata,
              last_seen_at = now(),
              owner_id = EXCLUDED.owner_id,
              updated_at = now()
RETURNING id, workspace_id, daemon_id, name, runtime_mode, provider, status, device_info, metadata, last_seen_at, owner_id, profile_id, custom_name, created_at, updated_at
`

type UpsertAgentRuntimeParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	DaemonID    string      `json:"daemon_id"`
	Name        string      `json:"name"`
	Provider    string      `json:"provider"`
	Status      string      `json:"status"`
	DeviceInfo  string      `json:"device_info"`
	Metadata    []byte      `json:"metadata"`
	OwnerID     pgtype.UUID `json:"owner_id"`
	ProfileID   pgtype.UUID `json:"profile_id"`
}

func (q *Queries) UpsertAgentRuntime(ctx context.Context, arg UpsertAgentRuntimeParams) (AgentRuntime, error) {
	row := q.db.QueryRow(ctx, upsertAgentRuntime,
		arg.WorkspaceID,
		arg.DaemonID,
		arg.Name,
		arg.Provider,
		arg.Status,
		arg.DeviceInfo,
		arg.Metadata,
		arg.OwnerID,
		arg.ProfileID,
	)
	var i AgentRuntime
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DaemonID,
		&i.Name,
		&i.RuntimeMode,
		&i.Provider,
		&i.Status,
		&i.DeviceInfo,
		&i.Metadata,
		&i.LastSeenAt,
		&i.OwnerID,
		&i.ProfileID,
		&i.CustomName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSkillFile = `-- name: UpsertSkillFile :one
INSERT INTO skill_file (skill_id, path, content)
VALUES ($1, $2, $3)
ON CONFLICT (skill_id, path) DO UPDATE
SET content = EXCLUDED.content, updated_at = now()
RETURNING id, skill_id, path, content, created_at, updated_at
`

type UpsertSkillFileParams struct {
	SkillID pgtype.UUID `json:"skill_id"`
	Path    string      `json:"path"`
	Content string      `json:"content"`
}

func (q *Queries) UpsertSkillFile(ctx context.Context, arg UpsertSkillFileParams) (SkillFile, error) {
	row := q.db.QueryRow(ctx, upsertSkillFile, arg.SkillID, arg.Path, arg.Content)
	var i SkillFile
	err := row.Scan(
		&i.ID,
		&i.SkillID,
		&i.Path,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
