// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tool_registry.sql

package lightweightdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceToolSourceCurrentRevision = `-- name: AdvanceToolSourceCurrentRevision :one
UPDATE tool_source source
SET current_revision = revision.id, updated_at = now()
FROM tool_source_revision revision
WHERE source.id = $1
  AND source.workspace_id = $2
  AND revision.id = $3
  AND revision.workspace_id = source.workspace_id
  AND revision.source_id = source.id
  AND revision.status = 'ready'
RETURNING source.id, source.workspace_id, source.name, source.kind, source.enabled, source.current_revision, source.created_by, source.created_at, source.updated_at
`

type AdvanceToolSourceCurrentRevisionParams struct {
	SourceID    pgtype.UUID `json:"source_id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	RevisionID  pgtype.UUID `json:"revision_id"`
}

func (q *Queries) AdvanceToolSourceCurrentRevision(ctx context.Context, arg AdvanceToolSourceCurrentRevisionParams) (ToolSource, error) {
	row := q.db.QueryRow(ctx, advanceToolSourceCurrentRevision, arg.SourceID, arg.WorkspaceID, arg.RevisionID)
	var i ToolSource
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Kind,
		&i.Enabled,
		&i.CurrentRevision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const clearToolSourceCurrentRevision = `-- name: ClearToolSourceCurrentRevision :one
UPDATE tool_source
SET enabled = false, current_revision = NULL, updated_at = now()
WHERE id = $1 AND workspace_id = $2
RETURNING id, workspace_id, name, kind, enabled, current_revision, created_by, created_at, updated_at
`

type ClearToolSourceCurrentRevisionParams struct {
	SourceID    pgtype.UUID `json:"source_id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) ClearToolSourceCurrentRevision(ctx context.Context, arg ClearToolSourceCurrentRevisionParams) (ToolSource, error) {
	row := q.db.QueryRow(ctx, clearToolSourceCurrentRevision, arg.SourceID, arg.WorkspaceID)
	var i ToolSource
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Kind,
		&i.Enabled,
		&i.CurrentRevision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countToolBundleRetainers = `-- name: CountToolBundleRetainers :one
SELECT
    (SELECT count(*) FROM agent_tool_bundle_head head
     WHERE head.workspace_id = $1 AND head.bundle_id = $2)
  + (SELECT count(*) FROM agent_task_queue task
     WHERE task.workspace_id = $1 AND task.tool_bundle_id = $2)
  + (SELECT count(*) FROM task_token token
     WHERE token.workspace_id = $1 AND token.tool_bundle_id = $2) AS retainers
`

type CountToolBundleRetainersParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	BundleID    string      `json:"bundle_id"`
}

func (q *Queries) CountToolBundleRetainers(ctx context.Context, arg CountToolBundleRetainersParams) (int32, error) {
	row := q.db.QueryRow(ctx, countToolBundleRetainers, arg.WorkspaceID, arg.BundleID)
	var retainers int32
	err := row.Scan(&retainers)
	return retainers, err
}

const countToolSourceBundleRetainers = `-- name: CountToolSourceBundleRetainers :one
SELECT count(*) FROM tool_bundle_item
WHERE workspace_id = $1 AND source_id = $2
`

type CountToolSourceBundleRetainersParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	SourceID    pgtype.UUID `json:"source_id"`
}

func (q *Queries) CountToolSourceBundleRetainers(ctx context.Context, arg CountToolSourceBundleRetainersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countToolSourceBundleRetainers, arg.WorkspaceID, arg.SourceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createToolBundle = `-- name: CreateToolBundle :one
INSERT INTO tool_bundle (id, workspace_id, manifest_hash, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, workspace_id, manifest_hash, status, created_by, created_at, revoked_at
`

type CreateToolBundleParams struct {
	ID           string      `json:"id"`
	WorkspaceID  pgtype.UUID `json:"workspace_id"`
	ManifestHash string      `json:"manifest_hash"`
	CreatedBy    pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateToolBundle(ctx context.Context, arg CreateToolBundleParams) (ToolBundle, error) {
	row := q.db.QueryRow(ctx, createToolBundle,
		arg.ID,
		arg.WorkspaceID,
		arg.ManifestHash,
		arg.CreatedBy,
	)
	var i ToolBundle
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ManifestHash,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createToolBundleItem = `-- name: CreateToolBundleItem :one
INSERT INTO tool_bundle_item (
    workspace_id, bundle_id, ordinal, public_name, source_id,
    source_revision_id, tool_definition_id, artifact_id,
    definition_snapshot, invocation_plan
)
VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8,
    $9, $10
)
RETURNING id, workspace_id, bundle_id, ordinal, public_name, source_id, source_revision_id, tool_definition_id, artifact_id, definition_snapshot, invocation_plan, created_at
`

type CreateToolBundleItemParams struct {
	WorkspaceID        pgtype.UUID `json:"workspace_id"`
	BundleID           string      `json:"bundle_id"`
	Ordinal            int32       `json:"ordinal"`
	PublicName         string      `json:"public_name"`
	SourceID           pgtype.UUID `json:"source_id"`
	SourceRevisionID   pgtype.UUID `json:"source_revision_id"`
	ToolDefinitionID   pgtype.UUID `json:"tool_definition_id"`
	ArtifactID         pgtype.UUID `json:"artifact_id"`
	DefinitionSnapshot []byte      `json:"definition_snapshot"`
	InvocationPlan     []byte      `json:"invocation_plan"`
}

func (q *Queries) CreateToolBundleItem(ctx context.Context, arg CreateToolBundleItemParams) (ToolBundleItem, error) {
	row := q.db.QueryRow(ctx, createToolBundleItem,
		arg.WorkspaceID,
		arg.BundleID,
		arg.Ordinal,
		arg.PublicName,
		arg.SourceID,
		arg.SourceRevisionID,
		arg.ToolDefinitionID,
		arg.ArtifactID,
		arg.DefinitionSnapshot,
		arg.InvocationPlan,
	)
	var i ToolBundleItem
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.BundleID,
		&i.Ordinal,
		&i.PublicName,
		&i.SourceID,
		&i.SourceRevisionID,
		&i.ToolDefinitionID,
		&i.ArtifactID,
		&i.DefinitionSnapshot,
		&i.InvocationPlan,
		&i.CreatedAt,
	)
	return i, err
}

const createToolDefinition = `-- name: CreateToolDefinition :one
INSERT INTO tool_definition (
    workspace_id, source_id, source_revision_id, public_name, upstream_name,
    description, input_schema, output_schema, operation_metadata
)
VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9
)
RETURNING id, workspace_id, source_id, source_revision_id, public_name, upstream_name, description, input_schema, output_schema, operation_metadata, enabled, created_at
`

type CreateToolDefinitionParams struct {
	WorkspaceID       pgtype.UUID `json:"workspace_id"`
	SourceID          pgtype.UUID `json:"source_id"`
	SourceRevisionID  pgtype.UUID `json:"source_revision_id"`
	PublicName        string      `json:"public_name"`
	UpstreamName      string      `json:"upstream_name"`
	Description       string      `json:"description"`
	InputSchema       []byte      `json:"input_schema"`
	OutputSchema      []byte      `json:"output_schema"`
	OperationMetadata []byte      `json:"operation_metadata"`
}

func (q *Queries) CreateToolDefinition(ctx context.Context, arg CreateToolDefinitionParams) (ToolDefinition, error) {
	row := q.db.QueryRow(ctx, createToolDefinition,
		arg.WorkspaceID,
		arg.SourceID,
		arg.SourceRevisionID,
		arg.PublicName,
		arg.UpstreamName,
		arg.Description,
		arg.InputSchema,
		arg.OutputSchema,
		arg.OperationMetadata,
	)
	var i ToolDefinition
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SourceID,
		&i.SourceRevisionID,
		&i.PublicName,
		&i.UpstreamName,
		&i.Description,
		&i.InputSchema,
		&i.OutputSchema,
		&i.OperationMetadata,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const createToolSource = `-- name: CreateToolSource :one
INSERT INTO tool_source (workspace_id, name, kind, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, workspace_id, name, kind, enabled, current_revision, created_by, created_at, updated_at
`

type CreateToolSourceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Name        string      `json:"name"`
	Kind        string      `json:"kind"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateToolSource(ctx context.Context, arg CreateToolSourceParams) (ToolSource, error) {
	row := q.db.QueryRow(ctx, createToolSource,
		arg.WorkspaceID,
		arg.Name,
		arg.Kind,
		arg.CreatedBy,
	)
	var i ToolSource
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Kind,
		&i.Enabled,
		&i.CurrentRevision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createToolSourceArtifact = `-- name: CreateToolSourceArtifact :one
WITH inserted AS (
    INSERT INTO tool_source_artifact (
        workspace_id, source_id, sha256, media_type, size_bytes, content
    )
    VALUES (
        $1, $2, $3,
        $4, $5, $6
    )
    ON CONFLICT (workspace_id, source_id, sha256) DO NOTHING
    RETURNING id, workspace_id, source_id, sha256, media_type, size_bytes, content, created_at
)
SELECT id, workspace_id, source_id, sha256, media_type, size_bytes, content, created_at FROM inserted
UNION ALL
SELECT id, workspace_id, source_id, sha256, media_type, size_bytes, content, created_at FROM tool_source_artifact
WHERE workspace_id = $1
  AND source_id = $2
  AND sha256 = $3
LIMIT 1
`

type CreateToolSourceArtifactParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	SourceID    pgtype.UUID `json:"source_id"`
	Sha256      string      `json:"sha256"`
	MediaType   string      `json:"media_type"`
	SizeBytes   int64       `json:"size_bytes"`
	Content     []byte      `json:"content"`
}

type CreateToolSourceArtifactRow struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	SourceID    pgtype.UUID        `json:"source_id"`
	Sha256      string             `json:"sha256"`
	MediaType   string             `json:"media_type"`
	SizeBytes   int64              `json:"size_bytes"`
	Content     []byte             `json:"content"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateToolSourceArtifact(ctx context.Context, arg CreateToolSourceArtifactParams) (CreateToolSourceArtifactRow, error) {
	row := q.db.QueryRow(ctx, createToolSourceArtifact,
		arg.WorkspaceID,
		arg.SourceID,
		arg.Sha256,
		arg.MediaType,
		arg.SizeBytes,
		arg.Content,
	)
	var i CreateToolSourceArtifactRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SourceID,
		&i.Sha256,
		&i.MediaType,
		&i.SizeBytes,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const createToolSourceRevision = `-- name: CreateToolSourceRevision :one
WITH locked_source AS (
    SELECT id, workspace_id
    FROM tool_source
    WHERE id = $3 AND workspace_id = $2
    FOR UPDATE
), next_revision AS (
    SELECT COALESCE(max(revision.revision), 0) + 1 AS revision
    FROM locked_source source
    LEFT JOIN tool_source_revision revision
      ON revision.source_id = source.id AND revision.workspace_id = source.workspace_id
)
INSERT INTO tool_source_revision (
    id, workspace_id, source_id, revision, endpoint, transport_config,
    artifact_id, secret_id, created_by
)
SELECT
    $1, $2, $3, next_revision.revision,
    $4, $5, $6,
    $7, $8
FROM locked_source, next_revision
RETURNING id, workspace_id, source_id, revision, status, endpoint, transport_config, artifact_id, secret_id, validation_code, created_by, created_at, published_at
`

type CreateToolSourceRevisionParams struct {
	ID              pgtype.UUID `json:"id"`
	WorkspaceID     pgtype.UUID `json:"workspace_id"`
	SourceID        pgtype.UUID `json:"source_id"`
	Endpoint        pgtype.Text `json:"endpoint"`
	TransportConfig []byte      `json:"transport_config"`
	ArtifactID      pgtype.UUID `json:"artifact_id"`
	SecretID        pgtype.UUID `json:"secret_id"`
	CreatedBy       pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateToolSourceRevision(ctx context.Context, arg CreateToolSourceRevisionParams) (ToolSourceRevision, error) {
	row := q.db.QueryRow(ctx, createToolSourceRevision,
		arg.ID,
		arg.WorkspaceID,
		arg.SourceID,
		arg.Endpoint,
		arg.TransportConfig,
		arg.ArtifactID,
		arg.SecretID,
		arg.CreatedBy,
	)
	var i ToolSourceRevision
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SourceID,
		&i.Revision,
		&i.Status,
		&i.Endpoint,
		&i.TransportConfig,
		&i.ArtifactID,
		&i.SecretID,
		&i.ValidationCode,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const createToolSourceSecret = `-- name: CreateToolSourceSecret :one
INSERT INTO tool_source_secret (id, workspace_id, source_id, envelope, key_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workspace_id, source_id, envelope, key_id, created_at, updated_at
`

type CreateToolSourceSecretParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	SourceID    pgtype.UUID `json:"source_id"`
	Envelope    []byte      `json:"envelope"`
	KeyID       string      `json:"key_id"`
}

func (q *Queries) CreateToolSourceSecret(ctx context.Context, arg CreateToolSourceSecretParams) (ToolSourceSecret, error) {
	row := q.db.QueryRow(ctx, createToolSourceSecret,
		arg.ID,
		arg.WorkspaceID,
		arg.SourceID,
		arg.Envelope,
		arg.KeyID,
	)
	var i ToolSourceSecret
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SourceID,
		&i.Envelope,
		&i.KeyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAgentToolBundleHead = `-- name: DeleteAgentToolBundleHead :execrows
DELETE FROM agent_tool_bundle_head
WHERE workspace_id = $1 AND agent_id = $2
`

type DeleteAgentToolBundleHeadParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	AgentID     pgtype.UUID `json:"agent_id"`
}

func (q *Queries) DeleteAgentToolBundleHead(ctx context.Context, arg DeleteAgentToolBundleHeadParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAgentToolBundleHead, arg.WorkspaceID, arg.AgentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteToolBundle = `-- name: DeleteToolBundle :execrows
DELETE FROM tool_bundle
WHERE workspace_id = $1
  AND id = $2
  AND status = 'revoked'
`

type DeleteToolBundleParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	BundleID    string      `json:"bundle_id"`
}

func (q *Queries) DeleteToolBundle(ctx context.Context, arg DeleteToolBundleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteToolBundle, arg.WorkspaceID, arg.BundleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteToolBundleItems = `-- name: DeleteToolBundleItems :execrows
DELETE FROM tool_bundle_item
WHERE workspace_id = $1 AND bundle_id = $2
`

type DeleteToolBundleItemsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	BundleID    string      `json:"bundle_id"`
}

func (q *Queries) DeleteToolBundleItems(ctx context.Context, arg DeleteToolBundleItemsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteToolBundleItems, arg.WorkspaceID, arg.BundleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteToolDefinitionsBySource = `-- name: DeleteToolDefinitionsBySource :execrows
DELETE FROM tool_definition
WHERE workspace_id = $1 AND source_id = $2
`

type DeleteToolDefinitionsBySourceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	SourceID    pgtype.UUID `json:"source_id"`
}

func (q *Queries) DeleteToolDefinitionsBySource(ctx context.Context, arg DeleteToolDefinitionsBySourceParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteToolDefinitionsBySource, arg.WorkspaceID, arg.SourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteToolSource = `-- name: DeleteToolSource :execrows
DELETE FROM tool_source
WHERE id = $1 AND workspace_id = $2
`

type DeleteToolSourceParams struct {
	SourceID    pgtype.UUID `json:"source_id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteToolSource(ctx context.Context, arg DeleteToolSourceParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteToolSource, arg.SourceID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteToolSourceArtifactsBySource = `-- name: DeleteToolSourceArtifactsBySource :execrows
DELETE FROM tool_source_artifact
WHERE workspace_id = $1 AND source_id = $2
`

type DeleteToolSourceArtifactsBySourceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	SourceID    pgtype.UUID `json:"source_id"`
}

func (q *Queries) DeleteToolSourceArtifactsBySource(ctx context.Context, arg DeleteToolSourceArtifactsBySourceParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteToolSourceArtifactsBySource, arg.WorkspaceID, arg.SourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteToolSourceRevisionsBySource = `-- name: DeleteToolSourceRevisionsBySource :execrows
DELETE FROM tool_source_revision
WHERE workspace_id = $1 AND source_id = $2
`

type DeleteToolSourceRevisionsBySourceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	SourceID    pgtype.UUID `json:"source_id"`
}

func (q *Queries) DeleteToolSourceRevisionsBySource(ctx context.Context, arg DeleteToolSourceRevisionsBySourceParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteToolSourceRevisionsBySource, arg.WorkspaceID, arg.SourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteToolSourceSecretsBySource = `-- name: DeleteToolSourceSecretsBySource :execrows
DELETE FROM tool_source_secret
WHERE workspace_id = $1 AND source_id = $2
`

type DeleteToolSourceSecretsBySourceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	SourceID    pgtype.UUID `json:"source_id"`
}

func (q *Queries) DeleteToolSourceSecretsBySource(ctx context.Context, arg DeleteToolSourceSecretsBySourceParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteToolSourceSecretsBySource, arg.WorkspaceID, arg.SourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAgentToolBundleHead = `-- name: GetAgentToolBundleHead :one
SELECT id, workspace_id, agent_id, bundle_id, updated_by, updated_at FROM agent_tool_bundle_head
WHERE workspace_id = $1 AND agent_id = $2
`

type GetAgentToolBundleHeadParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	AgentID     pgtype.UUID `json:"agent_id"`
}

func (q *Queries) GetAgentToolBundleHead(ctx context.Context, arg GetAgentToolBundleHeadParams) (AgentToolBundleHead, error) {
	row := q.db.QueryRow(ctx, getAgentToolBundleHead, arg.WorkspaceID, arg.AgentID)
	var i AgentToolBundleHead
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AgentID,
		&i.BundleID,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthorizedTaskBundle = `-- name: GetAuthorizedTaskBundle :one
SELECT bundle.id, bundle.workspace_id, bundle.manifest_hash, bundle.status, bundle.created_by, bundle.created_at, bundle.revoked_at
FROM agent_task_queue task
JOIN agent ON agent.id = task.agent_id AND agent.workspace_id = task.workspace_id
JOIN tool_bundle bundle
  ON bundle.id = task.tool_bundle_id AND bundle.workspace_id = task.workspace_id
WHERE task.id = $1
  AND task.workspace_id = $2
  AND task.agent_id = $3
  AND task.tool_bundle_id = $4
  AND task.status IN ('dispatched', 'waiting_local_directory', 'running')
  AND agent.archived_at IS NULL
  AND bundle.status = 'active'
`

type GetAuthorizedTaskBundleParams struct {
	TaskID      pgtype.UUID `json:"task_id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	AgentID     pgtype.UUID `json:"agent_id"`
	BundleID    pgtype.Text `json:"bundle_id"`
}

func (q *Queries) GetAuthorizedTaskBundle(ctx context.Context, arg GetAuthorizedTaskBundleParams) (ToolBundle, error) {
	row := q.db.QueryRow(ctx, getAuthorizedTaskBundle,
		arg.TaskID,
		arg.WorkspaceID,
		arg.AgentID,
		arg.BundleID,
	)
	var i ToolBundle
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ManifestHash,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAuthorizedTaskBundleItemByName = `-- name: GetAuthorizedTaskBundleItemByName :one
SELECT item.id, item.workspace_id, item.bundle_id, item.ordinal, item.public_name, item.source_id, item.source_revision_id, item.tool_definition_id, item.artifact_id, item.definition_snapshot, item.invocation_plan, item.created_at
FROM agent_task_queue task
JOIN agent ON agent.id = task.agent_id AND agent.workspace_id = task.workspace_id
JOIN tool_bundle bundle
  ON bundle.id = task.tool_bundle_id AND bundle.workspace_id = task.workspace_id
JOIN tool_bundle_item item
  ON item.bundle_id = bundle.id AND item.workspace_id = bundle.workspace_id
JOIN tool_source source
  ON source.id = item.source_id AND source.workspace_id = item.workspace_id
JOIN tool_definition definition
  ON definition.id = item.tool_definition_id AND definition.workspace_id = item.workspace_id
WHERE task.id = $1
  AND task.workspace_id = $2
  AND task.agent_id = $3
  AND task.tool_bundle_id = $4
  AND item.public_name = $5
  AND task.status IN ('dispatched', 'waiting_local_directory', 'running')
  AND agent.archived_at IS NULL
  AND bundle.status = 'active'
  AND source.enabled = true
  AND definition.enabled = true
`

type GetAuthorizedTaskBundleItemByNameParams struct {
	TaskID      pgtype.UUID `json:"task_id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	AgentID     pgtype.UUID `json:"agent_id"`
	BundleID    pgtype.Text `json:"bundle_id"`
	PublicName  string      `json:"public_name"`
}

func (q *Queries) GetAuthorizedTaskBundleItemByName(ctx context.Context, arg GetAuthorizedTaskBundleItemByNameParams) (ToolBundleItem, error) {
	row := q.db.QueryRow(ctx, getAuthorizedTaskBundleItemByName,
		arg.TaskID,
		arg.WorkspaceID,
		arg.AgentID,
		arg.BundleID,
		arg.PublicName,
	)
	var i ToolBundleItem
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.BundleID,
		&i.Ordinal,
		&i.PublicName,
		&i.SourceID,
		&i.SourceRevisionID,
		&i.ToolDefinitionID,
		&i.ArtifactID,
		&i.DefinitionSnapshot,
		&i.InvocationPlan,
		&i.CreatedAt,
	)
	return i, err
}

const getBundlePublicationToolDefinition = `-- name: GetBundlePublicationToolDefinition :one
SELECT
    definition.id,
    definition.workspace_id,
    definition.source_id,
    definition.source_revision_id,
    definition.public_name,
    definition.upstream_name,
    definition.description,
    definition.input_schema,
    definition.output_schema,
    definition.operation_metadata,
    definition.enabled,
    definition.created_at,
    source.kind AS source_kind,
    revision.artifact_id,
    revision.endpoint,
    revision.transport_config
FROM tool_definition definition
JOIN tool_source source
  ON source.id = definition.source_id AND source.workspace_id = definition.workspace_id
JOIN tool_source_revision revision
  ON revision.id = definition.source_revision_id
 AND revision.workspace_id = definition.workspace_id
 AND revision.source_id = definition.source_id
WHERE definition.id = $1
  AND definition.workspace_id = $2
  AND definition.enabled = true
  AND source.enabled = true
  AND source.current_revision = definition.source_revision_id
  AND revision.status = 'ready'
`

type GetBundlePublicationToolDefinitionParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

type GetBundlePublicationToolDefinitionRow struct {
	ID                pgtype.UUID        `json:"id"`
	WorkspaceID       pgtype.UUID        `json:"workspace_id"`
	SourceID          pgtype.UUID        `json:"source_id"`
	SourceRevisionID  pgtype.UUID        `json:"source_revision_id"`
	PublicName        string             `json:"public_name"`
	UpstreamName      string             `json:"upstream_name"`
	Description       string             `json:"description"`
	InputSchema       []byte             `json:"input_schema"`
	OutputSchema      []byte             `json:"output_schema"`
	OperationMetadata []byte             `json:"operation_metadata"`
	Enabled           bool               `json:"enabled"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	SourceKind        string             `json:"source_kind"`
	ArtifactID        pgtype.UUID        `json:"artifact_id"`
	Endpoint          pgtype.Text        `json:"endpoint"`
	TransportConfig   []byte             `json:"transport_config"`
}

func (q *Queries) GetBundlePublicationToolDefinition(ctx context.Context, arg GetBundlePublicationToolDefinitionParams) (GetBundlePublicationToolDefinitionRow, error) {
	row := q.db.QueryRow(ctx, getBundlePublicationToolDefinition, arg.ID, arg.WorkspaceID)
	var i GetBundlePublicationToolDefinitionRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SourceID,
		&i.SourceRevisionID,
		&i.PublicName,
		&i.UpstreamName,
		&i.Description,
		&i.InputSchema,
		&i.OutputSchema,
		&i.OperationMetadata,
		&i.Enabled,
		&i.CreatedAt,
		&i.SourceKind,
		&i.ArtifactID,
		&i.Endpoint,
		&i.TransportConfig,
	)
	return i, err
}

const getTaskBundleClaim = `-- name: GetTaskBundleClaim :one
SELECT
    task.id AS task_id,
    task.workspace_id,
    task.agent_id,
    task.tool_bundle_id,
    bundle.status AS bundle_status
FROM agent_task_queue task
JOIN tool_bundle bundle
  ON bundle.id = task.tool_bundle_id AND bundle.workspace_id = task.workspace_id
WHERE task.id = $1
  AND task.workspace_id = $2
  AND task.agent_id = $3
  AND task.tool_bundle_id IS NOT NULL
`

type GetTaskBundleClaimParams struct {
	TaskID      pgtype.UUID `json:"task_id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	AgentID     pgtype.UUID `json:"agent_id"`
}

type GetTaskBundleClaimRow struct {
	TaskID       pgtype.UUID `json:"task_id"`
	WorkspaceID  pgtype.UUID `json:"workspace_id"`
	AgentID      pgtype.UUID `json:"agent_id"`
	ToolBundleID pgtype.Text `json:"tool_bundle_id"`
	BundleStatus string      `json:"bundle_status"`
}

func (q *Queries) GetTaskBundleClaim(ctx context.Context, arg GetTaskBundleClaimParams) (GetTaskBundleClaimRow, error) {
	row := q.db.QueryRow(ctx, getTaskBundleClaim, arg.TaskID, arg.WorkspaceID, arg.AgentID)
	var i GetTaskBundleClaimRow
	err := row.Scan(
		&i.TaskID,
		&i.WorkspaceID,
		&i.AgentID,
		&i.ToolBundleID,
		&i.BundleStatus,
	)
	return i, err
}

const getTaskTokenBundleScope = `-- name: GetTaskTokenBundleScope :one
SELECT token.id, token.task_id, token.agent_id, token.workspace_id, token.user_id,
       token.tool_bundle_id, token.expires_at
FROM task_token token
JOIN agent_task_queue task
  ON task.id = token.task_id
 AND task.workspace_id = token.workspace_id
 AND task.agent_id = token.agent_id
 AND task.tool_bundle_id IS NOT DISTINCT FROM token.tool_bundle_id
WHERE token.token_hash = $1
  AND token.expires_at > now()
`

type GetTaskTokenBundleScopeRow struct {
	ID           pgtype.UUID        `json:"id"`
	TaskID       pgtype.UUID        `json:"task_id"`
	AgentID      pgtype.UUID        `json:"agent_id"`
	WorkspaceID  pgtype.UUID        `json:"workspace_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	ToolBundleID pgtype.Text        `json:"tool_bundle_id"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) GetTaskTokenBundleScope(ctx context.Context, tokenHash string) (GetTaskTokenBundleScopeRow, error) {
	row := q.db.QueryRow(ctx, getTaskTokenBundleScope, tokenHash)
	var i GetTaskTokenBundleScopeRow
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.AgentID,
		&i.WorkspaceID,
		&i.UserID,
		&i.ToolBundleID,
		&i.ExpiresAt,
	)
	return i, err
}

const getToolBundle = `-- name: GetToolBundle :one
SELECT id, workspace_id, manifest_hash, status, created_by, created_at, revoked_at FROM tool_bundle
WHERE id = $1 AND workspace_id = $2
`

type GetToolBundleParams struct {
	ID          string      `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) GetToolBundle(ctx context.Context, arg GetToolBundleParams) (ToolBundle, error) {
	row := q.db.QueryRow(ctx, getToolBundle, arg.ID, arg.WorkspaceID)
	var i ToolBundle
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ManifestHash,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getToolSource = `-- name: GetToolSource :one
SELECT id, workspace_id, name, kind, enabled, current_revision, created_by, created_at, updated_at FROM tool_source
WHERE id = $1 AND workspace_id = $2
`

type GetToolSourceParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) GetToolSource(ctx context.Context, arg GetToolSourceParams) (ToolSource, error) {
	row := q.db.QueryRow(ctx, getToolSource, arg.ID, arg.WorkspaceID)
	var i ToolSource
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Kind,
		&i.Enabled,
		&i.CurrentRevision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getToolSourceArtifact = `-- name: GetToolSourceArtifact :one
SELECT id, workspace_id, source_id, sha256, media_type, size_bytes, content, created_at
FROM tool_source_artifact
WHERE id = $1
  AND workspace_id = $2
  AND source_id = $3
`

type GetToolSourceArtifactParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	SourceID    pgtype.UUID `json:"source_id"`
}

func (q *Queries) GetToolSourceArtifact(ctx context.Context, arg GetToolSourceArtifactParams) (ToolSourceArtifact, error) {
	row := q.db.QueryRow(ctx, getToolSourceArtifact, arg.ID, arg.WorkspaceID, arg.SourceID)
	var i ToolSourceArtifact
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SourceID,
		&i.Sha256,
		&i.MediaType,
		&i.SizeBytes,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getToolSourceArtifactMetadata = `-- name: GetToolSourceArtifactMetadata :one
SELECT id, workspace_id, source_id, sha256, media_type, size_bytes, created_at
FROM tool_source_artifact
WHERE id = $1
  AND workspace_id = $2
  AND source_id = $3
`

type GetToolSourceArtifactMetadataParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	SourceID    pgtype.UUID `json:"source_id"`
}

type GetToolSourceArtifactMetadataRow struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	SourceID    pgtype.UUID        `json:"source_id"`
	Sha256      string             `json:"sha256"`
	MediaType   string             `json:"media_type"`
	SizeBytes   int64              `json:"size_bytes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetToolSourceArtifactMetadata(ctx context.Context, arg GetToolSourceArtifactMetadataParams) (GetToolSourceArtifactMetadataRow, error) {
	row := q.db.QueryRow(ctx, getToolSourceArtifactMetadata, arg.ID, arg.WorkspaceID, arg.SourceID)
	var i GetToolSourceArtifactMetadataRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SourceID,
		&i.Sha256,
		&i.MediaType,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const getToolSourceByName = `-- name: GetToolSourceByName :one
SELECT id, workspace_id, name, kind, enabled, current_revision, created_by, created_at, updated_at FROM tool_source
WHERE workspace_id = $1 AND name = $2
`

type GetToolSourceByNameParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Name        string      `json:"name"`
}

func (q *Queries) GetToolSourceByName(ctx context.Context, arg GetToolSourceByNameParams) (ToolSource, error) {
	row := q.db.QueryRow(ctx, getToolSourceByName, arg.WorkspaceID, arg.Name)
	var i ToolSource
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Kind,
		&i.Enabled,
		&i.CurrentRevision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getToolSourceRevision = `-- name: GetToolSourceRevision :one
SELECT id, workspace_id, source_id, revision, status, endpoint, transport_config, artifact_id, secret_id, validation_code, created_by, created_at, published_at FROM tool_source_revision
WHERE id = $1
  AND workspace_id = $2
  AND source_id = $3
`

type GetToolSourceRevisionParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	SourceID    pgtype.UUID `json:"source_id"`
}

func (q *Queries) GetToolSourceRevision(ctx context.Context, arg GetToolSourceRevisionParams) (ToolSourceRevision, error) {
	row := q.db.QueryRow(ctx, getToolSourceRevision, arg.ID, arg.WorkspaceID, arg.SourceID)
	var i ToolSourceRevision
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SourceID,
		&i.Revision,
		&i.Status,
		&i.Endpoint,
		&i.TransportConfig,
		&i.ArtifactID,
		&i.SecretID,
		&i.ValidationCode,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const getToolSourceSecret = `-- name: GetToolSourceSecret :one
SELECT id, workspace_id, source_id, envelope, key_id, created_at, updated_at FROM tool_source_secret
WHERE id = $1
  AND workspace_id = $2
  AND source_id = $3
`

type GetToolSourceSecretParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	SourceID    pgtype.UUID `json:"source_id"`
}

func (q *Queries) GetToolSourceSecret(ctx context.Context, arg GetToolSourceSecretParams) (ToolSourceSecret, error) {
	row := q.db.QueryRow(ctx, getToolSourceSecret, arg.ID, arg.WorkspaceID, arg.SourceID)
	var i ToolSourceSecret
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SourceID,
		&i.Envelope,
		&i.KeyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getToolSourceSecretMetadata = `-- name: GetToolSourceSecretMetadata :one
SELECT id, workspace_id, source_id, key_id, created_at, updated_at
FROM tool_source_secret
WHERE id = $1
  AND workspace_id = $2
  AND source_id = $3
`

type GetToolSourceSecretMetadataParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	SourceID    pgtype.UUID `json:"source_id"`
}

type GetToolSourceSecretMetadataRow struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	SourceID    pgtype.UUID        `json:"source_id"`
	KeyID       string             `json:"key_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetToolSourceSecretMetadata(ctx context.Context, arg GetToolSourceSecretMetadataParams) (GetToolSourceSecretMetadataRow, error) {
	row := q.db.QueryRow(ctx, getToolSourceSecretMetadata, arg.ID, arg.WorkspaceID, arg.SourceID)
	var i GetToolSourceSecretMetadataRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SourceID,
		&i.KeyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAuthorizedTaskBundleItems = `-- name: ListAuthorizedTaskBundleItems :many
SELECT item.id, item.workspace_id, item.bundle_id, item.ordinal, item.public_name, item.source_id, item.source_revision_id, item.tool_definition_id, item.artifact_id, item.definition_snapshot, item.invocation_plan, item.created_at
FROM agent_task_queue task
JOIN agent ON agent.id = task.agent_id AND agent.workspace_id = task.workspace_id
JOIN tool_bundle bundle
  ON bundle.id = task.tool_bundle_id AND bundle.workspace_id = task.workspace_id
JOIN tool_bundle_item item
  ON item.bundle_id = bundle.id AND item.workspace_id = bundle.workspace_id
JOIN tool_source source
  ON source.id = item.source_id AND source.workspace_id = item.workspace_id
JOIN tool_definition definition
  ON definition.id = item.tool_definition_id AND definition.workspace_id = item.workspace_id
WHERE task.id = $1
  AND task.workspace_id = $2
  AND task.agent_id = $3
  AND task.tool_bundle_id = $4
  AND task.status IN ('dispatched', 'waiting_local_directory', 'running')
  AND agent.archived_at IS NULL
  AND bundle.status = 'active'
  AND source.enabled = true
  AND definition.enabled = true
ORDER BY item.ordinal, item.id
`

type ListAuthorizedTaskBundleItemsParams struct {
	TaskID      pgtype.UUID `json:"task_id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	AgentID     pgtype.UUID `json:"agent_id"`
	BundleID    pgtype.Text `json:"bundle_id"`
}

func (q *Queries) ListAuthorizedTaskBundleItems(ctx context.Context, arg ListAuthorizedTaskBundleItemsParams) ([]ToolBundleItem, error) {
	rows, err := q.db.Query(ctx, listAuthorizedTaskBundleItems,
		arg.TaskID,
		arg.WorkspaceID,
		arg.AgentID,
		arg.BundleID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ToolBundleItem{}
	for rows.Next() {
		var i ToolBundleItem
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.BundleID,
			&i.Ordinal,
			&i.PublicName,
			&i.SourceID,
			&i.SourceRevisionID,
			&i.ToolDefinitionID,
			&i.ArtifactID,
			&i.DefinitionSnapshot,
			&i.InvocationPlan,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listToolBundleItems = `-- name: ListToolBundleItems :many
SELECT id, workspace_id, bundle_id, ordinal, public_name, source_id, source_revision_id, tool_definition_id, artifact_id, definition_snapshot, invocation_plan, created_at FROM tool_bundle_item
WHERE workspace_id = $1 AND bundle_id = $2
ORDER BY ordinal, id
`

type ListToolBundleItemsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	BundleID    string      `json:"bundle_id"`
}

func (q *Queries) ListToolBundleItems(ctx context.Context, arg ListToolBundleItemsParams) ([]ToolBundleItem, error) {
	rows, err := q.db.Query(ctx, listToolBundleItems, arg.WorkspaceID, arg.BundleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ToolBundleItem{}
	for rows.Next() {
		var i ToolBundleItem
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.BundleID,
			&i.Ordinal,
			&i.PublicName,
			&i.SourceID,
			&i.SourceRevisionID,
			&i.ToolDefinitionID,
			&i.ArtifactID,
			&i.DefinitionSnapshot,
			&i.InvocationPlan,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listToolDefinitionsByRevision = `-- name: ListToolDefinitionsByRevision :many
SELECT id, workspace_id, source_id, source_revision_id, public_name, upstream_name, description, input_schema, output_schema, operation_metadata, enabled, created_at FROM tool_definition
WHERE workspace_id = $1
  AND source_id = $2
  AND source_revision_id = $3
ORDER BY public_name, id
`

type ListToolDefinitionsByRevisionParams struct {
	WorkspaceID      pgtype.UUID `json:"workspace_id"`
	SourceID         pgtype.UUID `json:"source_id"`
	SourceRevisionID pgtype.UUID `json:"source_revision_id"`
}

func (q *Queries) ListToolDefinitionsByRevision(ctx context.Context, arg ListToolDefinitionsByRevisionParams) ([]ToolDefinition, error) {
	rows, err := q.db.Query(ctx, listToolDefinitionsByRevision, arg.WorkspaceID, arg.SourceID, arg.SourceRevisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ToolDefinition{}
	for rows.Next() {
		var i ToolDefinition
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SourceID,
			&i.SourceRevisionID,
			&i.PublicName,
			&i.UpstreamName,
			&i.Description,
			&i.InputSchema,
			&i.OutputSchema,
			&i.OperationMetadata,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listToolSourceRevisions = `-- name: ListToolSourceRevisions :many
SELECT id, workspace_id, source_id, revision, status, endpoint, transport_config, artifact_id, secret_id, validation_code, created_by, created_at, published_at FROM tool_source_revision
WHERE workspace_id = $1 AND source_id = $2
ORDER BY revision DESC
`

type ListToolSourceRevisionsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	SourceID    pgtype.UUID `json:"source_id"`
}

func (q *Queries) ListToolSourceRevisions(ctx context.Context, arg ListToolSourceRevisionsParams) ([]ToolSourceRevision, error) {
	rows, err := q.db.Query(ctx, listToolSourceRevisions, arg.WorkspaceID, arg.SourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ToolSourceRevision{}
	for rows.Next() {
		var i ToolSourceRevision
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SourceID,
			&i.Revision,
			&i.Status,
			&i.Endpoint,
			&i.TransportConfig,
			&i.ArtifactID,
			&i.SecretID,
			&i.ValidationCode,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listToolSources = `-- name: ListToolSources :many
SELECT id, workspace_id, name, kind, enabled, current_revision, created_by, created_at, updated_at FROM tool_source
WHERE workspace_id = $1
ORDER BY updated_at DESC, id
LIMIT $2
`

type ListToolSourcesParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	PageLimit   int32       `json:"page_limit"`
}

func (q *Queries) ListToolSources(ctx context.Context, arg ListToolSourcesParams) ([]ToolSource, error) {
	rows, err := q.db.Query(ctx, listToolSources, arg.WorkspaceID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ToolSource{}
	for rows.Next() {
		var i ToolSource
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Kind,
			&i.Enabled,
			&i.CurrentRevision,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markToolSourceRevisionFailed = `-- name: MarkToolSourceRevisionFailed :one
UPDATE tool_source_revision
SET status = 'failed', validation_code = $1, published_at = NULL
WHERE id = $2
  AND workspace_id = $3
  AND source_id = $4
  AND status = 'validating'
RETURNING id, workspace_id, source_id, revision, status, endpoint, transport_config, artifact_id, secret_id, validation_code, created_by, created_at, published_at
`

type MarkToolSourceRevisionFailedParams struct {
	ValidationCode pgtype.Text `json:"validation_code"`
	ID             pgtype.UUID `json:"id"`
	WorkspaceID    pgtype.UUID `json:"workspace_id"`
	SourceID       pgtype.UUID `json:"source_id"`
}

func (q *Queries) MarkToolSourceRevisionFailed(ctx context.Context, arg MarkToolSourceRevisionFailedParams) (ToolSourceRevision, error) {
	row := q.db.QueryRow(ctx, markToolSourceRevisionFailed,
		arg.ValidationCode,
		arg.ID,
		arg.WorkspaceID,
		arg.SourceID,
	)
	var i ToolSourceRevision
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SourceID,
		&i.Revision,
		&i.Status,
		&i.Endpoint,
		&i.TransportConfig,
		&i.ArtifactID,
		&i.SecretID,
		&i.ValidationCode,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const markToolSourceRevisionReady = `-- name: MarkToolSourceRevisionReady :one
UPDATE tool_source_revision
SET status = 'ready', validation_code = NULL, published_at = now()
WHERE id = $1
  AND workspace_id = $2
  AND source_id = $3
  AND status = 'validating'
RETURNING id, workspace_id, source_id, revision, status, endpoint, transport_config, artifact_id, secret_id, validation_code, created_by, created_at, published_at
`

type MarkToolSourceRevisionReadyParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	SourceID    pgtype.UUID `json:"source_id"`
}

func (q *Queries) MarkToolSourceRevisionReady(ctx context.Context, arg MarkToolSourceRevisionReadyParams) (ToolSourceRevision, error) {
	row := q.db.QueryRow(ctx, markToolSourceRevisionReady, arg.ID, arg.WorkspaceID, arg.SourceID)
	var i ToolSourceRevision
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SourceID,
		&i.Revision,
		&i.Status,
		&i.Endpoint,
		&i.TransportConfig,
		&i.ArtifactID,
		&i.SecretID,
		&i.ValidationCode,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const pinAgentTaskToolBundle = `-- name: PinAgentTaskToolBundle :execrows
UPDATE agent_task_queue task
SET tool_bundle_id = $1
WHERE task.id = $2
  AND task.workspace_id = $3
  AND task.agent_id = $4
  AND task.tool_bundle_id IS NULL
  AND EXISTS (
      SELECT 1 FROM tool_bundle bundle
      WHERE bundle.id = $1
        AND bundle.workspace_id = task.workspace_id
        AND bundle.status = 'active'
  )
`

type PinAgentTaskToolBundleParams struct {
	BundleID    pgtype.Text `json:"bundle_id"`
	TaskID      pgtype.UUID `json:"task_id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	AgentID     pgtype.UUID `json:"agent_id"`
}

func (q *Queries) PinAgentTaskToolBundle(ctx context.Context, arg PinAgentTaskToolBundleParams) (int64, error) {
	result, err := q.db.Exec(ctx, pinAgentTaskToolBundle,
		arg.BundleID,
		arg.TaskID,
		arg.WorkspaceID,
		arg.AgentID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retireToolSourceRevision = `-- name: RetireToolSourceRevision :one
UPDATE tool_source_revision
SET status = 'retired'
WHERE id = $1
  AND workspace_id = $2
  AND source_id = $3
  AND status = 'ready'
RETURNING id, workspace_id, source_id, revision, status, endpoint, transport_config, artifact_id, secret_id, validation_code, created_by, created_at, published_at
`

type RetireToolSourceRevisionParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	SourceID    pgtype.UUID `json:"source_id"`
}

func (q *Queries) RetireToolSourceRevision(ctx context.Context, arg RetireToolSourceRevisionParams) (ToolSourceRevision, error) {
	row := q.db.QueryRow(ctx, retireToolSourceRevision, arg.ID, arg.WorkspaceID, arg.SourceID)
	var i ToolSourceRevision
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SourceID,
		&i.Revision,
		&i.Status,
		&i.Endpoint,
		&i.TransportConfig,
		&i.ArtifactID,
		&i.SecretID,
		&i.ValidationCode,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const revokeToolBundle = `-- name: RevokeToolBundle :one
UPDATE tool_bundle
SET status = 'revoked', revoked_at = now()
WHERE id = $1
  AND workspace_id = $2
  AND status = 'active'
RETURNING id, workspace_id, manifest_hash, status, created_by, created_at, revoked_at
`

type RevokeToolBundleParams struct {
	ID          string      `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) RevokeToolBundle(ctx context.Context, arg RevokeToolBundleParams) (ToolBundle, error) {
	row := q.db.QueryRow(ctx, revokeToolBundle, arg.ID, arg.WorkspaceID)
	var i ToolBundle
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ManifestHash,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const setToolDefinitionEnabled = `-- name: SetToolDefinitionEnabled :one
UPDATE tool_definition
SET enabled = $1
WHERE id = $2
  AND workspace_id = $3
  AND source_id = $4
RETURNING id, workspace_id, source_id, source_revision_id, public_name, upstream_name, description, input_schema, output_schema, operation_metadata, enabled, created_at
`

type SetToolDefinitionEnabledParams struct {
	Enabled     bool        `json:"enabled"`
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	SourceID    pgtype.UUID `json:"source_id"`
}

func (q *Queries) SetToolDefinitionEnabled(ctx context.Context, arg SetToolDefinitionEnabledParams) (ToolDefinition, error) {
	row := q.db.QueryRow(ctx, setToolDefinitionEnabled,
		arg.Enabled,
		arg.ID,
		arg.WorkspaceID,
		arg.SourceID,
	)
	var i ToolDefinition
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SourceID,
		&i.SourceRevisionID,
		&i.PublicName,
		&i.UpstreamName,
		&i.Description,
		&i.InputSchema,
		&i.OutputSchema,
		&i.OperationMetadata,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const setToolSourceEnabled = `-- name: SetToolSourceEnabled :one
UPDATE tool_source
SET enabled = $1, updated_at = now()
WHERE id = $2 AND workspace_id = $3
RETURNING id, workspace_id, name, kind, enabled, current_revision, created_by, created_at, updated_at
`

type SetToolSourceEnabledParams struct {
	Enabled     bool        `json:"enabled"`
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) SetToolSourceEnabled(ctx context.Context, arg SetToolSourceEnabledParams) (ToolSource, error) {
	row := q.db.QueryRow(ctx, setToolSourceEnabled, arg.Enabled, arg.ID, arg.WorkspaceID)
	var i ToolSource
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Kind,
		&i.Enabled,
		&i.CurrentRevision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateToolSource = `-- name: UpdateToolSource :one
UPDATE tool_source
SET name = $1, updated_at = now()
WHERE id = $2 AND workspace_id = $3
RETURNING id, workspace_id, name, kind, enabled, current_revision, created_by, created_at, updated_at
`

type UpdateToolSourceParams struct {
	Name        string      `json:"name"`
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) UpdateToolSource(ctx context.Context, arg UpdateToolSourceParams) (ToolSource, error) {
	row := q.db.QueryRow(ctx, updateToolSource, arg.Name, arg.ID, arg.WorkspaceID)
	var i ToolSource
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Kind,
		&i.Enabled,
		&i.CurrentRevision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateToolSourceSecret = `-- name: UpdateToolSourceSecret :one
UPDATE tool_source_secret
SET envelope = $1, key_id = $2, updated_at = now()
WHERE id = $3
  AND workspace_id = $4
  AND source_id = $5
RETURNING id, workspace_id, source_id, envelope, key_id, created_at, updated_at
`

type UpdateToolSourceSecretParams struct {
	Envelope    []byte      `json:"envelope"`
	KeyID       string      `json:"key_id"`
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	SourceID    pgtype.UUID `json:"source_id"`
}

func (q *Queries) UpdateToolSourceSecret(ctx context.Context, arg UpdateToolSourceSecretParams) (ToolSourceSecret, error) {
	row := q.db.QueryRow(ctx, updateToolSourceSecret,
		arg.Envelope,
		arg.KeyID,
		arg.ID,
		arg.WorkspaceID,
		arg.SourceID,
	)
	var i ToolSourceSecret
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SourceID,
		&i.Envelope,
		&i.KeyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAgentToolBundleHead = `-- name: UpsertAgentToolBundleHead :one
INSERT INTO agent_tool_bundle_head (workspace_id, agent_id, bundle_id, updated_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (workspace_id, agent_id) DO UPDATE
SET bundle_id = EXCLUDED.bundle_id, updated_by = EXCLUDED.updated_by, updated_at = now()
RETURNING id, workspace_id, agent_id, bundle_id, updated_by, updated_at
`

type UpsertAgentToolBundleHeadParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	AgentID     pgtype.UUID `json:"agent_id"`
	BundleID    string      `json:"bundle_id"`
	UpdatedBy   pgtype.UUID `json:"updated_by"`
}

func (q *Queries) UpsertAgentToolBundleHead(ctx context.Context, arg UpsertAgentToolBundleHeadParams) (AgentToolBundleHead, error) {
	row := q.db.QueryRow(ctx, upsertAgentToolBundleHead,
		arg.WorkspaceID,
		arg.AgentID,
		arg.BundleID,
		arg.UpdatedBy,
	)
	var i AgentToolBundleHead
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AgentID,
		&i.BundleID,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
