// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace_cleanup.sql

package lightweightdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearToolSourceCurrentRevisionsByWorkspace = `-- name: ClearToolSourceCurrentRevisionsByWorkspace :execrows
UPDATE tool_source
SET enabled = false, current_revision = NULL, updated_at = now()
WHERE workspace_id = $1
`

func (q *Queries) ClearToolSourceCurrentRevisionsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, clearToolSourceCurrentRevisionsByWorkspace, workspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countActiveTasksByWorkspace = `-- name: CountActiveTasksByWorkspace :one
SELECT count(*) FROM agent_task_queue
WHERE workspace_id = $1
  AND status IN ('deferred', 'queued', 'dispatched', 'waiting_local_directory', 'running')
`

func (q *Queries) CountActiveTasksByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveTasksByWorkspace, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOnlineRuntimesByWorkspace = `-- name: CountOnlineRuntimesByWorkspace :one
SELECT count(*) FROM agent_runtime
WHERE workspace_id = $1 AND status = 'online'
`

func (q *Queries) CountOnlineRuntimesByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOnlineRuntimesByWorkspace, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteActivityByWorkspace = `-- name: DeleteActivityByWorkspace :execrows
DELETE FROM activity_log WHERE workspace_id = $1
`

func (q *Queries) DeleteActivityByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteActivityByWorkspace, workspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAgentInvocationTargetsByWorkspace = `-- name: DeleteAgentInvocationTargetsByWorkspace :execrows
DELETE FROM agent_invocation_target WHERE agent_id IN (
    SELECT id FROM agent WHERE workspace_id = $1
)
`

func (q *Queries) DeleteAgentInvocationTargetsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAgentInvocationTargetsByWorkspace, workspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAgentRuntimesByWorkspace = `-- name: DeleteAgentRuntimesByWorkspace :execrows
DELETE FROM agent_runtime WHERE workspace_id = $1
`

func (q *Queries) DeleteAgentRuntimesByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAgentRuntimesByWorkspace, workspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAgentSkillsByWorkspace = `-- name: DeleteAgentSkillsByWorkspace :execrows
DELETE FROM agent_skill WHERE agent_id IN (
    SELECT id FROM agent WHERE workspace_id = $1
)
`

func (q *Queries) DeleteAgentSkillsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAgentSkillsByWorkspace, workspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAgentToolBundleHeadsByWorkspace = `-- name: DeleteAgentToolBundleHeadsByWorkspace :execrows
DELETE FROM agent_tool_bundle_head WHERE workspace_id = $1
`

func (q *Queries) DeleteAgentToolBundleHeadsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAgentToolBundleHeadsByWorkspace, workspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAgentsByWorkspace = `-- name: DeleteAgentsByWorkspace :execrows
DELETE FROM agent WHERE workspace_id = $1
`

func (q *Queries) DeleteAgentsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAgentsByWorkspace, workspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteChatDraftRestoresByWorkspace = `-- name: DeleteChatDraftRestoresByWorkspace :execrows
DELETE FROM chat_draft_restore WHERE chat_session_id IN (
    SELECT id FROM chat_session WHERE workspace_id = $1
)
`

func (q *Queries) DeleteChatDraftRestoresByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChatDraftRestoresByWorkspace, workspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteChatMessagesByWorkspace = `-- name: DeleteChatMessagesByWorkspace :execrows
DELETE FROM chat_message WHERE chat_session_id IN (
    SELECT id FROM chat_session WHERE workspace_id = $1
)
`

func (q *Queries) DeleteChatMessagesByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChatMessagesByWorkspace, workspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteChatSessionsByWorkspace = `-- name: DeleteChatSessionsByWorkspace :execrows
DELETE FROM chat_session WHERE workspace_id = $1
`

func (q *Queries) DeleteChatSessionsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChatSessionsByWorkspace, workspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCommentsByWorkspace = `-- name: DeleteCommentsByWorkspace :execrows
DELETE FROM comment WHERE workspace_id = $1
`

func (q *Queries) DeleteCommentsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCommentsByWorkspace, workspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteIssuesByWorkspace = `-- name: DeleteIssuesByWorkspace :execrows
DELETE FROM issue WHERE workspace_id = $1
`

func (q *Queries) DeleteIssuesByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIssuesByWorkspace, workspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRuntimeProfilesByWorkspace = `-- name: DeleteRuntimeProfilesByWorkspace :execrows
DELETE FROM runtime_profile WHERE workspace_id = $1
`

func (q *Queries) DeleteRuntimeProfilesByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRuntimeProfilesByWorkspace, workspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSkillFilesByWorkspace = `-- name: DeleteSkillFilesByWorkspace :execrows
DELETE FROM skill_file WHERE skill_id IN (
    SELECT id FROM skill WHERE workspace_id = $1
)
`

func (q *Queries) DeleteSkillFilesByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSkillFilesByWorkspace, workspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSkillsByWorkspace = `-- name: DeleteSkillsByWorkspace :execrows
DELETE FROM skill WHERE workspace_id = $1
`

func (q *Queries) DeleteSkillsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSkillsByWorkspace, workspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSquadMembersByWorkspace = `-- name: DeleteSquadMembersByWorkspace :execrows
DELETE FROM squad_member WHERE squad_id IN (
    SELECT id FROM squad WHERE workspace_id = $1
)
`

func (q *Queries) DeleteSquadMembersByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSquadMembersByWorkspace, workspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSquadsByWorkspace = `-- name: DeleteSquadsByWorkspace :execrows
DELETE FROM squad WHERE workspace_id = $1
`

func (q *Queries) DeleteSquadsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSquadsByWorkspace, workspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTaskMessagesByWorkspace = `-- name: DeleteTaskMessagesByWorkspace :execrows
DELETE FROM task_message WHERE task_id IN (
    SELECT id FROM agent_task_queue WHERE workspace_id = $1
)
`

func (q *Queries) DeleteTaskMessagesByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTaskMessagesByWorkspace, workspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTaskUsageByWorkspace = `-- name: DeleteTaskUsageByWorkspace :execrows
DELETE FROM task_usage WHERE task_id IN (
    SELECT id FROM agent_task_queue WHERE workspace_id = $1
)
`

func (q *Queries) DeleteTaskUsageByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTaskUsageByWorkspace, workspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTasksByWorkspace = `-- name: DeleteTasksByWorkspace :execrows
DELETE FROM agent_task_queue WHERE workspace_id = $1
`

func (q *Queries) DeleteTasksByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTasksByWorkspace, workspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteToolBundleItemsByWorkspace = `-- name: DeleteToolBundleItemsByWorkspace :execrows
DELETE FROM tool_bundle_item WHERE workspace_id = $1
`

func (q *Queries) DeleteToolBundleItemsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteToolBundleItemsByWorkspace, workspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteToolBundlesByWorkspace = `-- name: DeleteToolBundlesByWorkspace :execrows
DELETE FROM tool_bundle WHERE workspace_id = $1
`

func (q *Queries) DeleteToolBundlesByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteToolBundlesByWorkspace, workspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteToolDefinitionsByWorkspace = `-- name: DeleteToolDefinitionsByWorkspace :execrows
DELETE FROM tool_definition WHERE workspace_id = $1
`

func (q *Queries) DeleteToolDefinitionsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteToolDefinitionsByWorkspace, workspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteToolSourceArtifactsByWorkspace = `-- name: DeleteToolSourceArtifactsByWorkspace :execrows
DELETE FROM tool_source_artifact WHERE workspace_id = $1
`

func (q *Queries) DeleteToolSourceArtifactsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteToolSourceArtifactsByWorkspace, workspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteToolSourceRevisionsByWorkspace = `-- name: DeleteToolSourceRevisionsByWorkspace :execrows
DELETE FROM tool_source_revision WHERE workspace_id = $1
`

func (q *Queries) DeleteToolSourceRevisionsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteToolSourceRevisionsByWorkspace, workspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteToolSourceSecretsByWorkspace = `-- name: DeleteToolSourceSecretsByWorkspace :execrows
DELETE FROM tool_source_secret WHERE workspace_id = $1
`

func (q *Queries) DeleteToolSourceSecretsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteToolSourceSecretsByWorkspace, workspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteToolSourcesByWorkspace = `-- name: DeleteToolSourcesByWorkspace :execrows
DELETE FROM tool_source WHERE workspace_id = $1
`

func (q *Queries) DeleteToolSourcesByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteToolSourcesByWorkspace, workspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeToolBundlesByWorkspace = `-- name: RevokeToolBundlesByWorkspace :execrows
UPDATE tool_bundle
SET status = 'revoked', revoked_at = COALESCE(revoked_at, now())
WHERE workspace_id = $1 AND status = 'active'
`

func (q *Queries) RevokeToolBundlesByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeToolBundlesByWorkspace, workspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
