DROP TRIGGER IF EXISTS lw_task_token_bundle_scope_guard ON task_token;
DROP FUNCTION IF EXISTS lw_validate_task_token_bundle_scope();
DROP TRIGGER IF EXISTS lw_agent_task_bundle_pin_guard ON agent_task_queue;
DROP FUNCTION IF EXISTS lw_validate_agent_task_bundle_pin();
DROP TRIGGER IF EXISTS lw_agent_tool_bundle_head_write_guard ON agent_tool_bundle_head;
DROP FUNCTION IF EXISTS lw_validate_agent_tool_bundle_head_write();
DROP TRIGGER IF EXISTS lw_tool_bundle_item_write_guard ON tool_bundle_item;
DROP FUNCTION IF EXISTS lw_validate_tool_bundle_item_write();
DROP TRIGGER IF EXISTS lw_tool_bundle_write_guard ON tool_bundle;
DROP FUNCTION IF EXISTS lw_validate_tool_bundle_write();
DROP TRIGGER IF EXISTS lw_tool_definition_write_guard ON tool_definition;
DROP FUNCTION IF EXISTS lw_validate_tool_definition_write();
DROP TRIGGER IF EXISTS lw_tool_source_revision_write_guard ON tool_source_revision;
DROP FUNCTION IF EXISTS lw_validate_tool_source_revision_write();
DROP TRIGGER IF EXISTS lw_tool_source_secret_write_guard ON tool_source_secret;
DROP FUNCTION IF EXISTS lw_validate_tool_source_secret_write();
DROP TRIGGER IF EXISTS lw_tool_source_artifact_write_guard ON tool_source_artifact;
DROP FUNCTION IF EXISTS lw_validate_tool_source_artifact_write();
DROP TRIGGER IF EXISTS lw_tool_source_write_guard ON tool_source;
DROP FUNCTION IF EXISTS lw_validate_tool_source_write();
